apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-community
  namespace: kube-prometheus-stack
spec:
  interval: 15m
  url: https://grafana-community.github.io/helm-charts
