apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.11.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 15m
  releaseName: longhorn
  values:
    persistence:
      defaultClassReplicaCount: 3
      defaultDataLocality: best-effort
      recurringJobSelector:
        enable: true
        jobList: '[{"name":"backup","isGroup":true},{"name":"snapshot","isGroup":true},{"name":"trim","isGroup":true}]'
    defaultBackupStore:
      backupTarget: nfs://192.168.18.99:/volume1/k8sbackupstore
      pollInterval: 0
    defaultSettings:
      replicaAutoBalance: best-effort
      replicaZoneSoftAntiAffinity: true
      replicaDiskSoftAntiAffinity: false
      replicaSoftAntiAffinity: false
      restoreVolumeRecurringJobs: true

    ingress:
      enabled: false
