apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.9.x
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 15m
  releaseName: longhorn
  values:
    persistence:
      defaultClassReplicaCount: 3
      defaultDataLocality: best-effort
      recurringJobSelector:
        enable: true
        jobList: '[{"name":"backup","isGroup":true},{"name":"snapshot","isGroup":true},{"name":"trim","isGroup":true}]'
    defaultBackupStore:
      backupTarget: s3://mthomson-longhorn-backup@ca-central-1/
      backupTargetCredentialSecret: wasabi-secret
      pollInterval: 0
    defaultSettings:
      replicaAutoBalance: best-effort
      replicaZoneSoftAntiAffinity: true
      replicaDiskSoftAntiAffinity: false
      replicaSoftAntiAffinity: false
      restoreVolumeRecurringJobs: true

    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.michaelthomson.dev
      tls: true
      secureBackends: true
      tlsSecret: letsencrypt-wildcard-cert-michaelthomson.dev
      annotations:
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
