apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: longhorn.michaelthomson.dev
  namespace: longhorn-system
spec:
  endpoints:
  - dnsName: longhorn.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
