apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- chrome-deployment.yaml
- chrome-service.yaml
- data-pvc.yaml
- dns-endpoint.yaml
- hoarder-secrets.yaml
- ingress.yaml
- meilisearch-deployment.yaml
- meilisearch-pvc.yaml
- meilisearch-service.yaml
- web-deployment.yaml
- web-service.yaml
