apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Ti
