apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: qbittorrent
  annotations:
    nfs.io/storage-path: "media"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Ti
