kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: wireguard-config-secret
  namespace: qbittorrent
  creationTimestamp:
spec:
  template:
    metadata:
      name: wireguard-config-secret
      namespace: qbittorrent
      creationTimestamp:
  encryptedData:
    wg0.conf: AgDdF/rwKFANlByNG4But/CCqBC0BlQECdh4KartOeFaraA5EdqTo3G59q5uaC3nPmtyWFrzisi4nHORJc4rLDnhkg4l183WA4uVkry7KX8clO5yxZ5MeufnOjS/Mus81ckf1D+KWwUz1Z+N5N6kEa65bcnX3umqAc+i9dzjP0Ns+1eTVHwsSKJB+sbaDCN4+EeTjSYPfu3or52iJ/UACvK3ZnfCRiSYOUwl2dzOhioIKZZ6IF7uLqrHPXcJtU0X9CgTgsKou5LIuj1cNkXhaJLUWfNAaXP66rhtsBxs3SQw4rEi06nqm5201wSK2r5DSFiG3ndLbgn/4titKN0J5fa/IGq0aUPCI4x71qFoWcbq/oQnItk5QLCERGykElslKsaDphZwkFLuUYA53hXEsmqduuNKRrXpn0d+ic7O4McwtdyZkK6DVNiI+kzjSL8BipZmoAZg6LUXHcV0vTqsSly50QzTOfNtUh19XK8eBuDAtWHbd0KhXOok5IWu63eTsFUgxbCPF7Ua2tVieMLqwc5zw3GFiCfmcE7LUjr0g8KBEoKKtNo5pDv8Znvb7LjcPNNxJF6MDMmQpA1Krc7HYaEnZNRisFpaRcgpI3Ds82TnX/TCT562dqvpsado7fPqHTeonyo/47T8ZfATgBbwvya8e+8BZdXpNmJL88KR7tCOTUYLWD8UBZYb9McC7YIef5XKhTe+dvZatp6cZ9cWyx4iWWsgwsNMZgF9fGDKg6KLjk2bLZ493pkjXn6tOedCWes8DNzPug/1bmzi/OKHlDy4k7kVCB2kQVNdQbgKHr5eA4ueG27/OjWcs3jQ9WtXt6hAw5ljeKbmmKLQruw6Ss02Zq7toourNBmJXmmeNN8i4em7e5BiEhzRDVNPmtrJUnW7qPkvi7cTZXnjshkEa3+HN2k3Z6oiFay/KJ1/UyfR3v83GIpAjh/CpYA2q3QDWc2l2+NEUMUJkVkCZC4gUkrP5LRYGvsIumnshbTgftqBzWexnSWiHBSOYbGf4li3ICwZlbxgU6j0w75K+bNCaKvXjawlHNtdD7zbpL5TMF4W2OiSD2ddjpSUXh0rnYahfvkEAWLjRJKL+Mw/lp7YJ8UHD/gqQM4nE/FHB3TxvOnp6ERLOWkquRWLiN2j6NXVZqXcZDxUu8hteJNRhqI2UDJinV0ErD3FucK800lB
