apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 2.x
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
  interval: 15m
  releaseName: stirling-pdf
  values:
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: pdf.michaelthomson.dev
          paths:
            - path: "/"
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - pdf.michaelthomson.dev
          secretName: letsencrypt-wildcard-cert-michaelthomson.dev
      ingressClassName: traefik
