apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:11.0-latest
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_ROOT_PASSWD
              valueFrom:
                secretKeyRef:
                  name: mariadb-root-password
                  key: MARIADB_ROOT_PASSWORD
            - name: TIME_ZONE
              value: "America/Toronto"
            - name: SEAFILE_ADMIN_EMAIL
              value: "seafile@michaelthomson.dev" #admin email
            - name: SEAFILE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-admin-password
                  key: SEAFILE_ADMIN_PASSWORD
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "https://seafile.michaelthomson.dev" #hostname
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
