apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
  namespace: media
spec:
  selector:
    matchLabels:
      app: recyclarr
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
      containers:
      - name: recyclarr
        image: ghcr.io/recyclarr/recyclarr
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        persistentVolumeClaim: 
          claimName: recyclarr-config
            
          
