---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admincreds-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgCwvQh5vH5l3stlui0BqxM0hHTAMTVIUQJ5MpABi9CvuHAzJaSnZIXSc2WxCcMNkM8M7D1KK0J8g9lnNMOY1fkz9YPL+HCk58Q18nLJxDsVV/1iAUvjpscL/L/wv046IiMEv93Tc2gd1MoOYq0wALbJgvhT578Xd53edFZLpSmhfAjNSmpKQ6aupvrf501LmLWNFhomNaUsJST7nnrHsfu+SbwY5c3en+J7xlcEcspyh/kT6su+lPBVNfvJhjR3SDb3CqUGLxt3OPfHbGFgksCQfTL+b836Gjf6Po8VUjv2a3IPaLdOS5Oac2Q23iW1WtMQqIaIcBed52lrskt7NURLMpzv7i/KqALoWXlEh97AbABb0l1BmPp0H/Zkg48L5/uX2V0laxQtr+ZqCfvKAidpyQPSzXjlsJOAkPES9F3OjQlW7eNLJuJhC0+8873bcobsf4XSgPcUyMp7fTJRDjKB0+DFrDqbpo+KszrqMtWeoB3o9EYO8b+pSNMTD1cDj6OOqtjZtQr3mo9T1JuWfsJ8r8pTQivz031gqi2Jciy7eGxAKWHcGZZujER9qJPMBxB4GM7xh/iQ4NJERPKRLk0ZHzBeVcZf8IQpjewpuLEfjzOsCBRF+5r1CL+QiGB1DVrNro/uuv+1kM4QYTuQLUNC/Nej96Jack57TIr8mrZUOlOC4g4cZJrRtkfV6hNTHdApVuUu9Tpno9ZWT8qK
  template:
    metadata:
      name: admincreds-secret
      namespace: vaultwarden
