---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admincreds-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAK4wkQSiBM01XhEwbnsYemvsPeMNE+tZHYe+EIrSpwL6TbSDPL3euiZnCBrl2lPWItVMYiCXGrCRePThkI5Ek/PfBCIzFq25hJXp54CYA0LsXo6Hjg6IATK4aXITr1rSsG6RJQpMlspWzwVkDDmKo5xgHlhTGuctoGl5/tKzf9XwWrJMrtBWurpPEMZWzEVpdeTO0CIJS/D1yZXsIqLm6g12pgtNMFl/PXP6cOBK5euwDwubBb63vj+1cWMGsJF2mQifKU9sDWUJ+b1CWBcCNArSqxaeeux6M60SG9/Bmp6PRd/lNGDqHVUf5ouVwHrAJexC920z59IyqWMw3LUqXm8DpVFmhrusiEK6j7bSiCEYFnZuv0pjzgHEeB0bDZalh7VmN91dgcfppPJs1504ohTu8CCWYtetkAmNiy7Sj8AI11CLmSwghHnxwSM8xqg0cQrXPbDhiHb44BwrD0G/jf+KGNMfmmRv8orqsDzoPVFzxQdD4RhP+uMQVUQbBd1a61Yq+NMsQqUXQaFnAXo94aQdf+TwH/c5luCzO8eaRGcPlomdZ4eACVthICq3+kglPjRV32fzQVIGcuLBU/Q18ec6gbjjto+aO2+RNhc5jqKptYDRx+DjF9aCm6OVYxuc4/snnWXoDgmMPHvQfXwtrKvrGN1muZ/Mr1WLTAMaJ+4upJaExRifDasHTQeSO+ykAvsb8gtxp35Fr+k2bg
  template:
    metadata:
      name: admincreds-secret
      namespace: vaultwarden
