---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admincreds-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgCJVPwzV2YGD7gK8K4XgCeUwGm7nXD1S7rLD2Sec6GulWiD7ZlhEOWzzzhbwIXoihWSTx49ZMrsFBWz14sV5ILNHgHjJ0XuXHsUMnQYp8+KVhGUakXQweus9GmlY0xnEF4Vy0Tsl4E/deKFp/mLNWsWAVEVvbfJgjH7KILUmNjyP0LcoedlAYB8qgq6NgjJ0uNkOkJE4VA8+wpjH7s2TcE+w4Nl/C1BpyRNpfshmWz3lpkUT5zDyWjrp95P17jsjeYBm7RP+Vkv4edq+VHIsM8/YJrjrhUVhhxSHHBAuDA6g/Sgf+mn9Y4Q/J4MWh8/iCqYagyWA2rD1ej13xBpeJ+XoSptDskP7nHYvmq2ML6MtpB/ZeURwWoPi+8lGTvXZZoQICbuQy9vTRrkHHnAJgUUQIc9Vic8Q3lqu2gSkMRkfyI/C0Eg6/mxtyHJ92ayiVWWfChXJIEw8d8LzbsCD62dXPs7+6EpP3NGodB/0bOA2vmHqkY9ndxOB9pKv/ka905BE2yL7JyyF/BF1FnRd79ZxgE9SYYOPVGWAZiXE0PFGnT1kIPWw5MULntszNlKi6i8olRy8v7IOSfkE0K35s10Aukt0Me4vreBqi1+1paNVMH+gNX+rZrc5OVT229BGaNu556/Il9bFEncjxNSHPs0pRpnzUnZK5O9DjQFTj+Na+14UASvR/OaZcX6uh0QQBC+6D2qjaMFdYa9HZ8e
  template:
    metadata:
      creationTimestamp: null
      name: admincreds-secret
      namespace: vaultwarden
