---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtpcreds-secret
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgAWl7Nzx6MuBrvteFVN45YOM8ezD76P390aUI5lCVyo/KU2gPUK2KMyijlqafPfSZ3JO4zUm8oxzpmNg/77uzzpxKuknErAXlnWWxx6lJ2H4oGrDCdb3VAAJAwNbUX1xFe/Y11DPnZ72c1Co2UQ5Mj2pCqMwKGOhBsuonl65z04cKwNAaD+ZGkWgbcaYqPFthAVCr++wGMdf32xPznGpjHGYGRBvZfv+Ws+iveMoWmJqpYz3RdVYOQz6x2bwNAgI+L9j796ywohrrPUTqiqTrjs919c9lys22ROgF6ymgu2diZ+Bi4SX0p0CYjP8kra6YSCkMmH6zHyjnkB+/bhB8i8TyUuPDMPeY82y4oktSs7sb0LnmEZBnqFAhPzBpQGGdA2RvsziwIHRrpsqKEsYa3Nq9Kp2gc85afXC/X3NjCz5qiCSy3VwcVNc1M5996UGHpC1f646o/jpdINx65L9AdecbhrNvplxb1g8IddVk6Y0Nt2pYAXkgl3NtjSROoRmo2K8ydUn/3wzXx7ofOx3O9N1rIXc8a/at3ElDLXDt3ygH1BJ9UvQN82Gsy28SGDT7x4enGRnYi2O0ayiODXFX/bpflxtnssK6mg9J9JGsRujXWKAw36zQJ4GxxUc0v4bZwSCbks3mk8hlmc/Z7k2PCV70h2RoLTCcgFklYm1EK85s3wmlFLZ4qRIcTjL8vW2PGogxk3NrcRRo2Zc0awfQ4fRm5xLayHiGXe
    SMTP_USERNAME: AgAadJJPnKsbQCOs59daHzGrZw86JqeupvU3FDW/mbdT79HWD+jjuhS0D5Xrs48mXItgJycNAZJg5axvp+h31mvN+1Gfj0L3UhcSYFxNUVmFlwDPiTKynQrUoN4bIXm8yZM/F6x09X6Ib758tIdubKuifotujRgoptwKkeiaoQtl1nODLJt7ec/zOcXkqqwxvGNWEdnumEWygxXNazB/C9xIkfcxh/rnMR/NSJmm1EtPLly9VjzVd0pWDdZFcqFI747KBjUWKc4VKLv0WjtcCCmHWScVrN56hTIajgrNQDdtgF0h+EV+CVUWkKltsX3ZZuNikoFS5UoM27TpCXe4YCg0g+RnQzfGRfyEiIk6BUIcvKJY3rEtaYXuFVgSbsiS1zs2X/h3uMLT0+mkTmeWqrsIrU9iOU9gxBG8g6CHbWIpbCRorR8nzBBgjflnNeKDb05EpkBGiOhQbLPRCIGc+54Wml3dbUhhftM0pKyVvq6wUxOl3E95O5n9qPFw0D49YES5QtaX/GQKzvazFkYCSJ/1pCIZaqh1skDOfmMckODbvw7rzb+syL5dNIo7NM2vzbvMYb7+O7qDm+9zK6aGq8JIRquL5LfEcnf5fO1rsW2k4upYhBPJk/UcKxVq5RHGXpmDLCBFzEr1LmPmynV5MxHXYsKtV8OIJzxFe7nsirVVwg/HycNJN1L43mYyFhZRZe2/ejoW8ql9b9p+0xZVT/cTRKKNZiHmEqp3BM+Ma+g=
  template:
    metadata:
      name: smtpcreds-secret
      namespace: vaultwarden
