---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: smtpcreds-secret
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgCJ7bEhGaT0bfip86cLE/fzVCOYxPB8SS5NzKjDXhROKkGiycD11y2dAozDH0O6fGvoi/e5fecV4b6FLk3xBtTRX7YBxlpQscmY7BZ2AABKhsUOefM5eIhszxDopbsBn0MYRb08ITO4IYswps0GbG3CMvDRKoPRgP6+Ek2ksmXBG2EpzGbyhznZz4JjWLhNhUVt2EHkGwCjJByvXVvtvny2PbLk5/fgsAcxZJqnkAlP9OqQMKa0xRSv8W8UdOUibNa28afz9fIXSF0G5LtnDADq6mVkTk7Q+KlZCuA1j+Ra82++b0KW6fDbaFXWysR7d/dCFjOG8LyB7f8rr3fALfu3k+MNV+8/sSl+Osm3wsBuSOY/lwUQUxDK2J7ZwVM1of1dK85F3ZepqkDGjR+/LGko8vfATlpuoRcj4v701EAoLhZHGOtUUoY7bjiMY672AzrvZaLLPm67u4OnJcK6xzUidbhP3BVv8IAAPHYwkrF/8Bn1LPhOU8+HLqFyW2O5czjnlNRBwYn+H6vUU+BKJa9jbBSPp/GNg7/MqCLcq8LIYuu3Mf3sVTXABlgC26jIWQh10LM/44+b5t4LCVt+mwrAom+g9ZIe1GQAhbhvcYYKfojL7cV8hQEHW45L9Il+f5XfwERz0BQJw15688RUMmK1ojlByGPnoEdDc9YhBQMamelTWHwJZAIZGKfPqgCxNB76pLUQ3a0lUImxKQe4OVQ9B9sIEv83zd/Z
    SMTP_USERNAME: AgCw8XfR4Ye+59cqMBHKVk2b/I29FoITL2b3WsGwZy36QMxJRcUtk0uZ3Q6/Hgv+4EOn8dI3yuSvivMkQVfFRKl83izfVCUyAe0ztpxpYRsgdNsoBISq1MceoCZhEkukX5kBzPvznLy0Ckxwj8hcRbYVd158aZDc59sa9i7lE3ZS4mjg+/fsSIg1DsSqEJLxNtNSWxaHWoZ7VHGPj+IlfjHby1i0b82X+3peWuypXkbVi82NN9pL8PDe4B4+SFuph/Ms1P4+TmwevQkw/VgGAtxmrNaTpi9dCA3/RIr0IUom3k8eLOEPbCWz6S0Wc+Jx6GQuA8zLJOEdapFKbSl/UDmEZQ8rc/pHh+GfB6s8eTtUzI8Cl7NLuVFojPJR4L6msh52UQYLjUXxqC9qtd18Z9q8bgk7E91kM/bSRsWyMkRBfxQSMyFLV7qIUJ4Nv6QSTRrhRsajvCKiTPYWT+N6OqpuqjtCChiixAT0gIsakbCYlJc3lXFeyt3pE13zirDXhHBIR0lZ4goeNYi9gvDo2rF5KWav45u6t+yRwys6XPVDfEtUtH2LAOWT/YkjMyw98/VR/MaABSLnsBHCsyyGos9JgA4DwIxkdIZi4jcgUUl337FlDw2qKVEDiAyW201FH2XO2saPP03hkSa0oy4kRXsJ3ax0UX9lWISeGyxHlX56M5uoCdWCtATp5ew0+ZabYekubKVWg4xTABWiUHDSZyQhxTEof3Igq3UYm5offS0=
  template:
    metadata:
      name: smtpcreds-secret
      namespace: vaultwarden
