apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: roundcube.michaelthomson.dev
  namespace: roundcube
spec:
  endpoints:
  - dnsName: roundcube.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
      - michaelthomson.ddns.net
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"

