apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: deluge.michaelthomson.dev
  namespace: media
spec:
  endpoints:
  - dnsName: deluge.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
