apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
spec:
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        envFrom:
        - configMapRef:
            name: sabnzbd-config
            optional: false
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - name: sabnzbd-config
          mountPath: /config
        - name: data
          mountPath: /data/usenet
          subPath: usenet
        - name: sabnzbd-incomplete
          mountPath: /incomplete
      volumes:
      - name: sabnzbd-config
        persistentVolumeClaim:
          claimName: sabnzbd-config
      - name: data
        persistentVolumeClaim:
          claimName: media-data
      - name: sabnzbd-incomplete
        emptyDir:
          sizeLimit: 50Gi
