apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-config
  namespace: media
data:
  VPN_SERVICE_PROVIDER: custom
  VPN_TYPE: wireguard
  VPN_PORT_FORWARDING: on
  VPN_PORT_FORWARDING_PROVIDER: protonvpn
  UPDATER_PERIOD: 24h
