kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: wireguard-config-secret
  namespace: media
  creationTimestamp:
spec:
  template:
    metadata:
      name: wireguard-config-secret
      namespace: media
      creationTimestamp:
  encryptedData:
    wg0.conf: AgC02zKiv9HIBMB7cmPgtx/mzUYUw7nKmp6NeUpblGsKI9v51P/Z1VrQlZNVmKlDOnYZu0aXGsH+CWmNyHJrR4jRCXtdZVG7y41tbHz2BxKRZGnbGPUKXop46LytXnuTL1NGrS00khQ9sI1nZKHd3vzZLiYXzVDVcdLpu+Mfbm/mPqlTszUCLI8MZ8usHGPDUVFovqA2OUdcnx+Z+VVmAoraDWfiDER5C0IIOm3Gdygu04WxNOU4Wx7y1NQR84D1xD6F7s+hTOQl2whpnoTpEbJ+RXFXBlpcf1J9S4V32Q09jE7s8Kq5f8wbYcuyzfoykiCs7RSy9a6rqgwCbNFtjUVGAmr6Ex3cLtBwpJF6mZ2fWhIqTonGAHpsSmtUOYZy44/K5axdGvdz479WNyqsaQg4WYfQpFwjSTWxv6q/4cYSRe0C0ukSkiFwuVa9IeBpG6XLR3nm/e+6LZ/qHs9Iv5iOgyAZXYLHYbEUdyhX1PQTFfVoAcIQUXvefoxyDAf29oX0dj6/zKcvKUSQMX6YoNsbqRpX7vR/d4NDHv7j615XZNiDsiKDNVZf/EDaGhuROQvrCn2dZQiIjzA1k6mTaB42soXfCx/KYt2moTGlLblhDJoc1BwFd1tp1RabfaVgZuXDTx2Gtkt9q8NvRpM26KdAgXzc4JxDKhzQSRmm9rPxMqldi3opqAuArk9xBnL2fgrLpxYdZ2+T1FnQOdg4coGbngj/6CApJ9yUodjJZGouYwuN5OVw4mi3Rifd10rLemSjfaL1KZsMuHwtsMINPHTOnEQSSdiZGExduZt8rOgFcr7Z9cf0IUubh/kC7uzq1K0Bz5Z+6A/x1O+pTkfa2eBP15ZBfC8YFAojc6fCTA8+WDLYXfJalyKT+IdaH2OU1H1wZtMXd72c1hLWJF5jG/hBy0iPTb8bK1wZpmWpuYRKuToEpLd/3niPY43F6ci+QsbKXHdlHe+D3JPpHHboGCkObNzS5y0Kj6TgYuKdR8BqrSsxZPNYN8ng4EZpLS9Az3KQU3x/pG/zX6qUuFWoPODS/ZShNKi04lZLhWgLRX5dypgGmSI6bMk6ELOdPZgSQupphEykysmFf2T323j9FuFSSfBzuCzBL3ef+Tn37jWoHSz0aXMaMCLmoqsWwFSoYn1zwDLV/NaFZIEbTwOn6Xq6U0tNn+DT1/P/sBFM
