kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: wireguard-secret
  namespace: media
  creationTimestamp:
spec:
  template:
    metadata:
      name: wireguard-secret
      namespace: media
      creationTimestamp:
  encryptedData:
    qbittorrent.conf: AgDOZEDPObCxcy62EMno7OffD9DVz2TVySgD3BR8MNq//vAbXkJszxoI2/4r/EhYSfiBem/4P+JZ9BBgscrh+FfE2yYkQdRx7RaQQgvy32l4xUyfzCuhz1mcpHhaNxdmSMgb8Jm9rf/Lw1lFZn0A7Te4tV21usw2L8+Rcz/dFseVUeiUhL0Hsawp1BtUH8fEFqseY6reRsYnHXt85uPDORiy8SaWKoJevgrzpBPLa/rf/d+Cnr5RJwCXV3q7q0e47fbKD7nVDkSIFsxF4Ar5D06d9mB+E/JMuXMRJL5tfLjCuk4H4QpF4jiXCF5p1HOzL2otElZeADJh/PRFMhRHAkvbfHhD73j5FM+RVeLBTImx9i3YW25SdDGNLeYdAUeua2x4nQwDSBxON9MtXi2sWqedwgusG7CPNStWSD5s7gZzEm6JkZvKb0mu5zoiUsdV7bJtskrL1GmFW2odcvvfi1gaff9iFOqsxm3jC5vXmsfUrIEMphmhNlrfj6i3x9UTIKETOSVsLAm1Wburq0johRiaEZ0zb2bfHEaNF60bl+XJioX98BCaW59h9yrdzotxmHB9bVcSZm1AWjhQ8s9V6Z6m84OlQ7HSZdg5jBiaTAPNLQ+halzGkqGvN67gv+i/r/OsKqbOeBHm5agdipK+hCOxHtkuGL9/G8oz2XtQNI7QMsDdOA6CmjxjMXXnu0lrxDWdGuS0RhTX41v4Gz0b8WxxFztY4Fzw+KcmMLgM47YQ8SChDOTYnpOhuQcNHCCU+9bgfj+p0kl0xr3tzEzJYqrw+ZewliELhlBjrr03SDiUIMpN0Mux++7oKFbPuwmt4stdHQ7VF896j2MPkcnfKF+pgyrHfUsZYlRSAQC0KuWmxU6AxkimVbm2jxkNbxYrFEkomNY47CXU6XLGT+HA/rWkmWK4mU+lFDchzvJPs0TksJ2mvCwrOHjip5S4m3k5PK1SdqqyFleLs85yEHICqyJAt3eBb/KT2WlPb8cQlu0lj1mG2aU40qdyd6/1jbD0Bc2elMrniQ17u5syKmIIE09ACGa7O7kv94jvnvzO1kafFrz/pJ8aLKIdBQlC7+Uw1wnsQHF5hxx426qpnqZ95hPxvpNpaC/cpTJAtH2H3kota4vlMN2I5/9LEPwuYxtYaE6Km06SHF67/kohx9h8PVDk5h920ewrrQNuKQnb
