kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: wireguard-config-secret
  namespace: media
  creationTimestamp:
spec:
  template:
    metadata:
      name: wireguard-config-secret
      namespace: media
      creationTimestamp:
  encryptedData:
    wg0.conf: AgBl96INYxQD4Pr5dxYnRmUfhfgCT6v+R+anYAvk/ETJT6RbEF9AhFB7hOe0blxDxLo61R36P7vh9DpCSBP23JHVEZroIW6uT2M9l8hrGEgVcjZ59d7oCI+/OJnKsFJfBJsBvQRX5WFG25Mr0qXFFYtKVisP2uZrZa/vIZ1Cz16N89Lmbqy8CXSKP4R5M89KrqyH0q85J4kg9NtsZlh9mfWfelb96/BwbWVNuAP+dT3dvx/L0uWgvSj07ks8sxDVlBUJ5hccA3Z6Rg4x2x1tRl5sXFTuGmnkNYR6fFCiomt/YJCczRzF7hUgL3LLml8Sk33xlX8u7dNK0J8byYvEokSD3ZDxLsZLmFTgps3gj3yKa2Q8dRhXZp4o+OBUHT2DFyrNWdw0Km6EAMwJ13G3Lvmif2TXoronbYa8JA+mcV93LpOC1Aubj1QjFTkrK3/4u3DIPK0XmjXS6TeHLD5Rxx8VQIojwWeGTEJRCuvSE2vrxeqv1KQ2Q7OuOyFjAxxlpdVKBdXNnrYAg/yT0zTLZuNBeKRgCCykX0CM+sB/72f606i2ZNLqWI4NAivk99y19Yk7M+iw92qWecAfk1QwYwwdUKUZLqVOtYToHpOKAhZULYy1edTwRbZo+tx+BB1c0z1KVD6j3GiyjDifNME+h5PNLmQplMDHeKZd2mZxaEkwAe++brktnySKkxHxSOMizxkN2wVScqN7lwJfjswV3WOwGcl0V6XXGf59XP5qHDDIAfbYJN/2e//fw1ccYMNrhMFCt3eYvzufQLcCDGsSQxuJa69z4NQT6L4P5LwKCzIef79mJ3ZrTQXMsU55eg42AKPLsympV5GJ8UAYlviGd3n0quLb/LsG0HbnNhw+iHdQw6gtfQWxXI3pdBzx+d4Cel0nS8eyRriBPNHUYN91aJo+afFre/ADMNZq6aqW4eoUmgpHuIjkfVBkvRWQiDCLJjJvb4JcdgwxJUjzfGU3rLKX/G0cGHzXySMwZaojQS3cE0AzGMcSlybSDbEbeDtBKzDhJ4cE44Tv8qVGRyihScEE84dXeRdU8flz8i36jGbD7wA9ID80QfP8NhyU7HS+z9xhnzgo05FWbQun+E19RSXDfTg251s7UshT+/4y3XXU22aD2IoWTG+Qd6A5/KAXf02YGBkkDN1pz0ANKCvK1EdfOWe/42pKGYqaf/z+
