---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-env-secret
  namespace: plane
spec:
  encryptedData:
    REDIS_URL: AgBaZQDyQumwFC1azkLRLy72aCcbZ1ZzsLBRucpwaEidS5ATdw67+AtKhvnRdFaHoTCV946mvlemFScfxQIjfiaVxMGIB6jMO6YRE43gtiJLgLS/q+RMjg9g762m4NfPsRb2Lggp9yHPTcoT6cs+CrNblv5aGPGrn+yZuzXx1JfgGk5Oh73WdL1VPOraVeZyLPDbUNRnTm++WwaEbl//Gfwa6pCkTqrBSBYK4p0gSsG1ZrsQw02zUhMvpM1Fz3H7pkylu/klyCIjyIqQwJ3a56jTGyyqCg3/Okm4pSzH51Uz3N9Yynu+8MnOWaYQPx9NQDPBQh3gBa2D5GTtG8sB9dI9qszeS4SI9p/0ekcjooPg1yD8a+T2D0tN7UErNc1vxC01KrqK+x2t/HYus4roYtECvO+MkiGy73NaGFY9Qz3av3HPugicqHzeLuNItdAo9w35Lx01xqwZY4YkaeE4ES/UGs+GyeUhIYxJY1yqPMWT0i9uACdIJ3u60P+eyn2nl6UpmxgTYgUptGbScazvMpp7sUfWzoWb6tV6MfFhGIh5TgBQSP3AJu/RufT7klpX0ueL07hYXeMvJc7fjLCJL9ZvF9C4IG7WRUJHdOzoG0V939OY2kB3iW/orKKqS4y3LJWJnaom0wpiteAESpUeZ2k5TZuwHIm+XeAVO7sCUNF2qQL+BeZR5M6QbP+CNGkGAfDtfn+jjSur++QdL1hRkDfNzelTwgHEltxjawoQnj3WZpD4so5/D3inSydmM/qd6WFqJlPM
    SECRET_KEY: AgAF+HDaceujZw57X2MpK2AnOSqAdQuIDur0+G9tUebLwRj7GQfaieolNERh+x51yk4J/1tmMyiJ/nPJuI3UClVSWIO0cIrwswnUpF/y+vY0bvNnna66TK0raH+redtC3QuiwJYmDKsjgmq3gRohleJTyrqJLvUemJj24yyI73s5EU3lCdAUW8aKwt1WxEyDIjmnSIcdvZy9lpK8vs+emb75Wct1HXriSroPq3jooKpXIA49H4NdSKkImVl3d775dCulKcARYVhtpsm1XfCG7cLDDzBfVHo/pDJDZZ1uy6EaLQ7wYYqt5GL2pI5tPTXySzPgVy6QAd65IbJJuB/KrBR7iyb7opDOP8A+pwiEDAgXAzGYDyGy1Hg5uRcJR/le35O+DXbGO6ZdtSa4xBpwUMVhw+uHNv8Q6/yPMqb28eHzqJ/GYf+Fna+XnU5vvLwVAv6SXNA2dag7XL60GwxAz1bkbdcNWFZpBLEMdNa3AL0kiBR+fEbnra85ICwX2GYANZeYvP/kj55x6izPzGprQ6KqfUlP9f3wUs8fRF9U8DaBnPEdV24A3dcBREKBYg5urSLV4f0NYmFX9V4FCKhAZmX+4VfCdboqgZqXACNeW7a08w+aoOHTZhx55Qe6M6Xeg+FxH+rBToFX6vQfNrJ6mj0GNc0VxWSBUmwgIBUaVH+mEjsgzSKpuWaZzAsjJpoWAcjopFSTJUWILFzmZM3c0ELppk/3cCho/ToMinRcouvX99n6NDiB2liGAjur3p7nJsV6Au1uR3Vcng==
  template:
    metadata:
      creationTimestamp: null
      name: app-env-secret
      namespace: plane
