---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-env-secret
  namespace: plane
spec:
  encryptedData:
    SECRET_KEY: AgC4u2ARpXuA7mboPqcmop6Sk2Ue6ia89KlSYfMW8j/J+8/mkPeT6UxhNQOYceWWo1Nuvpw4lhb1MLtM2hBzZ4jlQsLc24STLSyDH799aqUa05QPWU0QhoxuLNQ1tQz82enVt+7grVPgSbwSt/WjxmrBXLbiCUx5AW+xdLfPAo+qy6jOOxnfNYWu1xHFiLJhTXCxWzrd5PfWAYXJkmt2lOPNR30TggBJpc6FpEob7j4zrID0LLtAuXkBrpBwFZy2gD60/c4c1jquBRqwgxwt/n1cJWmzlV5WPdBRQJm5YtHXSHwhbnHTk3u9I2ejH1p0v6Wzth+o4iPLAbQBs2807bvO81RHODIZ/Ubd/uh2aEN9FmdoEkqNVxT+jqFUKu59ai7G0dKeUdv66w9cBiKiwscp5E/bdrV6MGNmy0A6HFSqVBW/m32C+RGO2L0RpKuVza68tmj5kevTBiT3T/PUE+yj09fZstUsPY42GMcNx+l2A6mtx1Nt9j2NTKOejTjFq8EWkTgKawUosvC6Mz/sjAMbq8jLKHC3zLrv5FXB3IgG4hcaX7DW0YK+xAN6FCCd9qgO8sW25Aj8xQejsOVczuM144pcR+r5PuzwcUtgGpfxOoP28A4T9sJ17SZ/P0kQKXf/fMdCLgfhoCWi83bossvSpr88p/xkrYWuZbVFrCayiRLCnjRsjgCNF2C0oPz7oPCv3i3WzfzqMu71EHLFX/0rib05MpJM7OsD+4jTLRHMKyjGtZMDrdWdKMlTN84fuhprnQcjfeRSWw==
  template:
    metadata:
      creationTimestamp: null
      name: app-env-secret
      namespace: plane
