---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app_env_secret
  namespace: plane
spec:
  encryptedData:
    SECRET_KEY: AgB7/hJ6aOpAoyYYWKomZMhyejcmPTjhMMyhRwnxrXfX3yWKJAhB0g7fszsMa5pYyAKdhu7ha1IPDHariajiJAuGhssJGdhiz8DP8tYL6BIoGc5I64yntlQezGNDtbM7ceUZEWVMx+lxXqsahfA2oz4ahPLvmBonyzIHsx5Xe36A3JyMyIPpz2sS/y7Ob02KSXVRxlN2hyOc+88W7e+RMNwh4HUAATN7hGu2LtbwrkK9HSPjM/stcwCnVPYm4jxeNz59WN8wC0pqNJySj/UXtJCLWc+f2QwFoVQSB+mBuSqHl0762jtf+Vi2jUyDAffjPFTgx5LWop/LWJfndi2z80Q7jcshuqNaRoltnm5cub8XTXy+rv4VeIa/f8rBx713nMGfVF2P6WE6UXpx7Z4G4gEK7+1OtLEIAvWJLb0FO5+wOdstr6vXaKupzoeI1Xi0/59boW8GNt1Tjk9aioJXsnS0n/V0XaXPqccUTh3up0YaqJrd2BXkRZNVjm6C99Bbbn+08g8SHT9n+jpXYRPE/S089NZaZOnrQ3HdS/WZY4k2i+ohEH1c1S6xcRwan76s14HSx5IWzkQ+twmRwSpiQnXkDoKD4Gw5SwoyPTevs16DSu4KVEdmv0oQ/l0o2htMzchXdqL4/WzyaCGVUF+FBVTIRAM0AGhrVbSETvFIn3A7qLqKyIa+kSFGuHcWQEd36VWBUUKFtZsUvgpGE9gsFwMm6D+fm6aiVoAylSJancmsMUKnchWJ6gwkNRZdiwykf5G8chyW6FCFsQ==
  template:
    metadata:
      creationTimestamp: null
      name: app_env_secret
      namespace: plane
