---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: live-env-secret
  namespace: plane
spec:
  encryptedData:
    REDIS_URL: AgAt/7LpgUA5YXliY3wVMTcSjmO8fQuz9s41LBdFrRDZTgyU0kyYlHAlXLG3XsmY5V2B/4cw4oK/7Skerclpf7d7ZGgFH1FlePdG8K8mTjdCJG7iGlCx9xAQx3SwZ/N8TDSpZVM+RMjiPvii4oCF0gCgbcNW6Rjlw2/IIraHjkblkJZO0crH9emvIGVJiDVh7dorDtA9kG0j6ix+ZQR7Am/IEo0LafX7vTnnkEpeiJbaG40o6Nuz4uwXcP7eDKW5jmwKnJxijqzZsdTXDdUHtwrLPTDPtiYuk8pbTPz/kaDGd43VbJOMU3mQdW/a0mX+2IMBDYWHq0eJpgKWehdxwwBZmmLRHzP85ns6nComXUN5oCtHll3aQfG06CGMNHx3I1EDTfGwPwbgpKSscr1aV5XAM3v0SYj1pou+R513xxnXgu5RjU7BumJvUnfdB+in+/BrcXPWy3Y24S++ssYV41VKo2e01izoPANScWJ6ZTJtSBSGv+EGhikkDXUDvj1ioKV44XUo9WP9UntY8/NWD/5kOz9wHVYVDxzl5PPwTo9aULxV+ivNpWlK3TKfid0sSt30jLBkfrfuPgCAabKXeMHf9y0ZgiUePqHHWaJ92iS7DjaUQ0oiHx7bz3n3tzz5klbAtD4YdcVkKwvD6lkfHjfbftYshykOj4IRe5DxqNHXQWqS2gYKe4j4LmAaAiszWO8clgKnPDSPpvzeFwBJw3iPh1KT0EY6OZIyDAfN2PEZU+DfhBeQESVtC7pmw7gdBMAg8ViK
  template:
    metadata:
      creationTimestamp: null
      name: live-env-secret
      namespace: plane
