---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: live-env-secret
  namespace: plane
spec:
  encryptedData:
    REDIS_URL: AgAbBLyCQ2ire8ru4sGbSpYqF9L+nCQ5lZF7hHMvldcJmTss0JhdUjbrfx0uZiXZK/rqHtK5ghzJLO0TwVyc52UpIuMEJIHEefNPUi1bT6n6D3MiinCor5j7cg335l75Q1r7K2tgw7QD8w00CSVyyFQHokCqk7P8YIvL2UJAmY4kpjeZZ+Rp9J33REO6Vj3zxhqLyOdtz31Nj44p7MfFPu5ub7hCRYnIHnWDS8nverAsOLlNoCtATU5J7EEkkUKhnQTWM/5pB0N+YaanB+OJqMcucwysf7hJwhU+kjgLdt6h+tftt5k7DOIgAQDjg2tmo4mkrMYtfDQNEJcf425xO2RhnRNmUb0kvEXyHOBlIvO1ClJwtEEiT5EQKJHhQsKn1hxvdstokZBRMHhiczN0qyz5v96uAJA6zZGx7dqbF9gb3NCeyVxAZ52aw+qyWk1G2e1iWThlHAWVf3JRxDJQ70RXFqaiwCaPC8eoeoo37sLRyewNr1Jyup7vjLFiIU5gUttifBTbngxwCAlW5J7xJCh226NRgfP3aWn05OS12CbN9exrjGHdgo+1tih7NZs4ttvfAOlWWUcezEYhhdu5TYtWWT2qVKqqV08pRlN9CWunv1Gng5gbyPr7QDAmrk4Tt0VH6RZCJlaz4u2+BFv9M7EPzY/ve5l4RNjKIs3Li4LunqwaIJsiEB+ZusvVqaopgbq7CuXGBIXEyhMokdAs1gVZUhavyWKwiZF1cKu7/qzaJxy9mVsHTzIUj+eU9DTWacQ+
  template:
    metadata:
      creationTimestamp: null
      name: live-env-secret
      namespace: plane
