---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: live-env-secret
  namespace: plane
spec:
  encryptedData:
    REDIS_URL: AgAnxbTGZ94Or2te9bITHGnmCFtBie9FomHyu6EbpFLGoHYqXGW/DeXExMVSdPMMKj68imu4U8C4dQkJ/EwDPUJIwEv9UHa1rE8fuunY16YiAyeRphrCrIrcBmicayhA2bKmmdNQfcfv7cNxNjUlX12E0f+gs7iWwkHpxa+a6QbvhplMEjmwSnP/tHsH7V0ho2KQomVH0q1riY5WQm95qYlfkv2lb36m7B6EXtY0JID8/OHlLhhsvUWjmpefkdL7Zvr+FgRkoEICzfwygdYgArHLCFmGQcRwl7VOTC7HjsgIP3UXUKHIvqIV0BIvCroclNOPiym5nbmTkgRl66lVE1Cwho1/KwD4ar/14jMdeYj9QVdrZiykcUuwQFsLe6of1SVWT+xm2+k+iP+Ke4vbsE6cPoweFA0LoReCz12bzET3smceQHktQ39OcdZVQ5cShvTkPNMx1oH0Qq+upWQFtNM9hs3BZmbjeK+gdbQY4Uy1EZeXKU6sZgN0AANAXGbvs7xPcjeTcyt0R4UI5m+HwXyFiRTyrGyzzdq7DuRKT6sTSPtq5gXa0vTNcL25Mb1UCr+S/LXqDL0oKIOQLDcyaPmQBk+FP8JSR7gABiBttNcRB2A64mBPCOzNcVaY3EpTBVWa4+mX4yvMSBUVrum1nWH0vU/Ddr30XKOZU2zMlBsoXzMmkvdyGGvHE9L9HhbBuVe8RUuJELGX9DQoo3HND8de5eyiNhZQSzjlnDhisFnV7KZzdUIvuV1xk4YJxdqVukxg
  template:
    metadata:
      creationTimestamp: null
      name: live-env-secret
      namespace: plane
