---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq_secret
  namespace: plane
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCwDLFMeFOodk227sdD3+i4NMMCIhwNHS+gKYzB+g+N+30/JCQGy49W/wGbT2cjHnP3yzAI/fpIuKV6VcDjXKRna53vLEnoYSBRHqjAcmHCpfztn1zO4+nb5lNvViZacVxUG09nyGdZzCvIsrIVTQUOLkBSfCKH/FBrCBDjYNbRggayvrwVuG+PXZGOHgSHUoJPSlP9RhqYchplxwbFFvY05SbpMN++PsQ5BQ3gees34rGXs9kjGq+PQ2z4T19707eEmoUp9YZIWjcNMkfwulQtI6Q/vI2AMZ5A6kFPyAkfRuvCLB646z9fOIOEXI3YKQG3iYTR+cskOvZ+SwzRnkF6BoBYcccMmQIfrwuiv78+6d9sBb08XXrnH5DIe2wlObAK52UjGE+M2g1qJT+CYNplFjP0AWlc4IOi4iTgSlJSv8ZbxrnmubOzwiPdhJ5B/KPrXvAms8KggiPHY4y0NB6QjBympyfKD1eRyz+C6Qj50SFL5rproVMYBf6WEy6fsnPMxHLyiIRJaXxaTherEk+ie01goCNYKY+XnwMHf4WjGBoCC/x1vCe8haVExbDn/I9xpFXxQLxbvGtRUijJOxy85HV/XWboNWar2FuhyRaHouQke5KDC9nUIjVLV7g+tZtHWmxFEIG0nfssopCxJwk97UYprribsffw1C4qf+ppEKLI7lMNW2i+jX8MQspNh4gPTWhM8516Wn/tycN7K/HPUCbKvHO7Cs24iCmWZTjb96JM38GnTVtLKFQcIU5mKcuJ3gNDs/vFXg==
    RABBITMQ_DEFAULT_USER: AgCIFZFJKhznciySJUegREMfSDretf8hlfGEa7DEQwCouEg0vfA+6ZnR9YRBlxqHOtddmZfGa6Bzhb6f+gs6LHREKPrUza2R3eNLvgxjarIJdgLq++RbTzQv1PbW2LuUOU9zInC07ynj0+m2mwsH5WT+udMnZhW8qS3mPexf9cQGqDDUcAx5G1Gi0N5EtJn7LfLeZw2B3wXxzL65hRjwGC8WW8BxmFuSOcL2aSagFnwJxaozaJjCNT5XZDg2Ahz7/QymyInMhxoz9zpUMdyEFl/TQqyW1HQ8936C/azLEBrR7Lob6j/02cp2S2jDQ+TjYBWr/MJs60Gy6DrTd/+82L90Z7Povoa6PuIM7iD2qfmOQs33Su9vr/9C1oJS+9wu9jHTy6m/vJd7AwEYoEQ/X9YN6iIJAqcUALkBAKVdfVbAzCQeWS8+ITIsQdGJRahjFGqDOeI2IRC8oiWlYe7b9z9+pHyfbAX+8/Of2JcxiM7BlK47uLbWdb4IxBtkHF1NZGOKd7T1Y4+vLaCbLrjd9F5CZlW9cG61IUekc0HQAgbAVUc7o3rsaFg/fhg8xPRB8lF8jb2Yu7JeKkDm7DvFJW4SJFpRIN6J/3GD95UhUH1NBqhLn7FKM0tk3Jgg3WNHtH//R1Ict0R1x9dB5jJW5twE7LN4hcCh/Om81BCo5MsSLzdenT7fRpOFNRwJ0/gcJ8jmVkCt9w==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq_secret
      namespace: plane
