---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: plane
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgC9aw4MniGdc6CQgM4R+IaMqi2JEtT7MQkUm9rDKfBCqnnSCICgbsGMFJjn4EYTPXptboUIIhdVsTOe8B/7JrWUW4tpz9Nb2lnP4V64OjpHUGm4cwYLen+u381khplLRhxu5ffk8efS2iqK6XHDqb3QcDDmED6NQpgkOdlOgYpHvNMT18SP5adzrBtX7I1yfJgcpbF0KOWUPO0hv/oxmNR6IfDcXL2F/WRUWPVv8/IYgiTmpGwVLe16prfc6jnxTcNmJattS2WZoJMYKLCHck0FRo5VmanA5fUtpJ51rGnL2He10tdT2R3AJZjGzOJXeimOIzmu4KhKffWa+qD35KunC4vc050zuRS19sKBix2r3TlvO7ndjhIkfmDmgeZSK0yoUVBH4AFI9apLXObd2JAVFgbMZgobIl/QArGnO52ayKmtPgV+//tnW82IhJFacJol0s0XrNnvn/5/ywCDam8iXfRQRKwCnud6cpn6UyJB82HOVF0++wzfrFyxQkG1NwVAmKykPEs0YYjevvIaCKsul8C3Y1CwYFvPhHv+aLfQmEpUotNK2R5z/EGBaZLyd9nEF7oI7ec1IyEvvmGkICA2FhJWfweppaVTpjKesgJINVPOVqoU8D35aE4d3GkW6hm3tP5VTfcQeHzDGZrTCp8f2o6kv5btXv5TGBkPmY5P8ZAMWZrcXJYEPbB7Pkor/pRZq+f8gYTOMabgLicFZTk6vmza1ShY16dHZnMUbn4Y8O5/vQkx26vf0jURMOgAHKjcWC60pQ==
    RABBITMQ_DEFAULT_USER: AgCwr7uiCorzr+g3LGpcrQpav1/sJXbvaYn/i3YFfoHP4KIx4HHAFOdZbjbAwRmR8UCNO/Yd/eD6+S79BVOi3D0PbG9o6d4eaNzSdfk5HPdTx2FBXUzQ1Hz0/kqGJsEPMy21jSOKnl8eBXVyxGjv4oaXOSrtkUp42P0KRo3YOGqJeteOP6b/nOYzItj5F7CT2cJXstyr5dZjsdkF2l26mt4NPlD1h4uDBa4o5WXVoRZNbtxI+Bd6n9X4jJ8gyCeDqNYNHtl69umxGEPGMN7PoP8KUHcSU4gOmpNtSA99aQQfZeRQNQrKARCza/IscuCDyYaT0e/FL/npMyd7EseeurQYdBZYYaSRIlI/gVlk60w8bOwNxdOJIWs7a99RI9r/SR48J7/vNVvCxVoafOUU5ojzFCDZODFg1vrUq5qCLietfv2zgPKntLrHMPuCcaEdoDNu7GfE4cSEV8PWRS/Kp7yW7TJ3u0kzwyW9WHPoujqwsfn5Gi1RR0JKXqYw3FsaNN+I019rZNn4JUM4N2f5dh4hLxpHah+TiXETBoM3Px1lZzLrchoq3TPrrauy4hmj0lwUCReleRb1MdiQ6mph78rKSthASRaj7UMYwnb4ldXzCBqZaB7NvgeZAbFTTZpUomYXWI6CCXlC79rnKjzFiOO43ZpYQqyjLz8+qGPOxPy3gsS+bzJGRu1imV+l1c6LtTyEsjdr9g==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: plane
