---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: plane
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAwrA6CGzwfm+rViSRBr7Ua6ea1O28Wm+oIBAqRijiT/F+fYKd9JnHBmlIUKlIjPyZ4AKZUT/GI08wJZVRmCDk5XPsQMWZmmnRlZzqm+S+zRJCtELuikOAVrXqsh5BqQsfPZCeIieZ6563E6AhmGdfKAZNfxUoaryHY7UUh34Dz2LtLeSc+PlswlFXHWRzUziKuEMUSzola6qBllmpCkROXFl0CbiCQ/w6ZEfcRwE3avzLqrCuf+N/fIFyWOEGSWsh7goLHiVd1tQ2ikl8OPA4CdOxPcz+LQ/BbNzM0bVcVsSmiIhxfyAfy8/TK3UJVc0U9ExaCMVqJ8dGl33CQQf36eCH5vc5SItx341uAKumeb/5qxKude39MUFiQ+mB1Kz3dY/XdCrJa+r+mE0PlhQHnO1vGaZLvcT7xVzvRRrGcpYZBr1yvB4I96xDa8H9k6ALC3dV8q303ORgKe2kSwKEf7zsu3lY284/ckrI/CEko5VKuYRZOiSZ4fDokw3JTjwxeEn0v1EAPMX5VBiT88hLnsuTaQ5KxnPy2k5KTBAwbh12wpmVPa3CDuq/IwtHsSujG0arheH7mxdBYD+agxPqWgYh5NIYccb6eiW6B1u0bt734lEC2TgYpMjJp8ycJYf+gborCEsaHeN+TZQn87phNe/aSfmP+Y4QT5BKjK4P7uWObVY9Jk+Och+sGxfi5r5sUpKADozkGJgbMdoDi8tGDqWx54Pe38e3sbTWPsec/OATWhpw/dSkFDusdENEVbueKnmm2Vp/rmQ==
    RABBITMQ_DEFAULT_USER: AgACuyPc+js2oSY/DxDkbOFbl7Jw3VCdpNjKNzzAAaMP53qjq+Xli+veIp5GkstDDXAha5oZL4lPp3Wc1l1gEVR4o0JgC21dx8IIFekcfm3DJCrXsIWnpD5RFywsUqCVGTd0vBPCOFoPGyvbWGJ+jc5P8TADHW3huf+oaEoEK/WnvYaPmV2jo+L1YeasB1ctidE3PtuiytJnAiSHMhbMIKtxFgoY8iK6Tn3Dh0mgknf7Or9Z6uXcApSOpcQtOCfYIQvy/frXBA5+hSdhnqG3XM/G1TyGrdkVIyIhhvIKRv0ugJB0nQZoWNMWluGn/W83aOvUjkT+BlRiNUFtb0O4LC6t0lsp7foX14UxP2xOIRt0IzcD9UHRAP+cji6ND5Zx7ptfxYfiP7sr7mqiNRFC9tQvR8rKYxNxWHX9bDE7WFRvccQs4zB5ei76KSJXaZnuyD1hWQJmp7fd5eauwdFYGG4aZtEYGf4zmzh9EbqJvopiUrMzCnh3U7z+AIkaYCEMKP1RV2DS1hrP3HlYWnxBMTni2gL8BSXe2LqCJQqo4zL3Zm/pqib9MTPFVfgu3dypn7GZLeFRkaE0NBxsMwHJYxHx9kCqTYddWyKSiMG6ON7cmNUEVIcNDcW9YL8BcyoxwSe7OmbxcRKNXWUc4flHkD/mYx3KBcdHUMX3cfwgewWCA+Ka8x8nLCo5mhU8j76QFTZXFbzSNQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: plane
