apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: calibre.michaelthomson.dev
  namespace: calibre-web
spec:
  endpoints:
  - dnsName: calibre.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
