---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    key: AgChrdxPNneS1prBs9CFCAM41sDLAKf7+C9OUtP6XZVBVdk/TlW5idKKotafdIp7C2sANZQtT/rZ/XRFc5G/gTQjBQtbxRa/P5zvN0BzxFXz9LhK8SSs/C4taZjWXWEnhG4Pv7cnvjSAnDj7gsUc4pVKANZEsIy5CJsdnhNDrsvcvU6ZheWeyJR8DZPOSWdaxvVm8DG1OldQsQd1/Xj2Ye0TViB9IHwzQ5ww1Q1etaN5eH7IFfLGwWZL0se6KxqAR/rpDCLT5qDRbWzKOF5CD/2o5fyAOaVcHvcB9fwKTWJqaLnAXEyOLyGsj898jHvT9nd6UC+5oAnaOqmSPRPe+KwPVGwaWaE7zhl09RfkeLmwi6RlUXjhjLyb9vNYuwJ+h8ME+EHPrZ3jBf74y77tSn4+6z/yWzCQ/t21RIb8USKys0bAeSXbEOpcKM4uwZE8taPCA5szzOyqATdB73Inuh4hi4b6Fl7CNMcdB9Ixe4WL9PS2d//juYIf+DT7ChArnvrrUcmG+8dXuygeE94LB2q3+46yAAvlo48S3NDZYsefLab9OVAUVoYp4zy+OGHhTmkYe962h7Dk7U3GVCA8A66nZMTFu93/o2ZIlMWg1XoLrV2i/NDgf1h/XoOaroNSXXZIR3Og+3UT9nzjZ2JShvORDXPI282A+j89gMe7mvu4ynL6/aNnHBYMY7cpq7c1w1gg4OYPSSLvWvkgsx4cBiMNtoVesP0xkD0Uj5quUWqBXM9gnI8yANf6xkr4paUme7d9AA==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
