---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgAuAf8o8Ye2EQlblMcKE0PoR2jRBR3s7T9kvRkSCcHFTjKc0Xk5vQX3Q5umBU1lIcKd7gSLgxmMFJh5GTUcVXlgkCyPpRF3gx85KFITY/Em4P0kOLU8Orojbp/PF5rZ48ADHiQ9MojzOfOPswRCBCCSMs4x6hnU4/Sb+F7h6Bm0qbwr4SEfqgaDxI8a6EhV7oYxG/GT9VQSlei2enc2ZCkRIjcztbeWBWtl369h2lLNdoqmOh7tvk2l+HzMabcE89AQnYSR2SCwyuHqTyTmPlrOC1Ilg7he2BW+791G6Uqd1LUH8kXFencaFfqHfG8sN0y1gT3NvFyNmPELNcIWIBg22upGoWODAa5np5S1l6QpPMbK9cc3A/TLsAjfNoqEObvvFmTqe/4kzvspRMgfCZRRyFv0l+A98AorY9wpkeL0qYLnD4mec21mrHT0texzLuzBsVGO2zklfbXvgq5HQpKTH8Gfy1t1E6Gv6NRTpPutvSZ9/Dw5m2tqXdZ/XrJW2gTZq1x9eTfScK8KE1CPM3FAuk9u3XZn2el5Ghlb+Aksddf/9C/8wCrNGpW8iQ8W3fKvABULt1WBeV55oao3um1JM/ECXaK1EnAng/yoJTjrkyPcEezjVavnVgcK2kjqa0k2DpBuxJqwBqO6aDxszwjnVT398wTCC6iHxFc+lMOkADpXovMJzKG+o/90M8fEzhO7lfZr5/6jrPrmDfE2VbumUN0tRrsNUheleyoz4Mf/w2j9N5YrA9cNCdF+mqDNE6QWpA==
    username: AgCihBT3nofvZvoVECf4wZtjEy4zkHuRAAgAhWNr4rdapbf+77e+JUG7g/52+L3OQ6HG+Wx4G5b+3G+boCZojmUEqn0iVH8JIDx1XAajT68xxMh37a1LdriBzMSkLJmMaRzWEL4toGC/R43bMP3uTievEWoeRfzlXg9+XFfj/V9/ty+Hwe6NHzfLVum5OrCA5+UWa46Djz56m1g7i3CRk605jntTSrd0gBPnhvpAXynpdiMUTceDXUN/t1xc4LuDSLM5rrZnAje+JdThTemTToRuY7HpazmZYKfIu0COo9BsacMzF6prJ6KzuGhLBsH1eTiI7oWPfhmZ/9c02YmbjtjadQVpjgiN/xm3iACtPGIur93HpM3DiJrP2LUTIWJ04YsTDt9ALSlDpAlIoOCq9rhL/RpXZ+gRbe+cNWmggyMir7FoMkfdEBjUZ+7Kun7CgIwtNYqmTUBGQL7YzEknJiZcZwj9OYnEXW/Vabh90tO1OzKzLLPSrL8jfthrqEZB+6BjGnDxOFkbgiKPE8gUCunnzPAWCjauK+TejubfrC0LEF1zo/F71xoBNkoBSkyI2j3qNwQslUQDSmeUFhvb4u0PHxdIcrJTePM1BiJNIkLotiF0YmANozO3AWSLaPUE0Txv2TwxRL2LIpRGOho6uAv1zEsGFMp1NrbxlL1CAnG0eHHIxakUT816a6l3ofJIaUbKYBmnUPzLrjE=
  template:
    metadata:
      name: authentik-postgres-credentials
      namespace: authentik
