---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    key: AgC3YkBq4rTPfO0uJIDDC+vyLuNYDEc01vAYzIx4KBrUkJ+iKEhkiOYTakHMTGZYMdXseUxGQ+s41Rgs+obDHRif9Y9mjOqsqyHl0zqsKPAKWsnvP4jofQhg+rbQM3SflO443ysOEyROAiV0JUI+vOjjCQOkfEwrv2GRlKe6yoYG712/g/BVTG0de54jqc+/Wlryqsxt+z8IuJhQv1dV2dciBpF2SjR8001iAnvl4Oq3/98mm8skCxiUfuDyPGZU9ao4vKgDXVrkISi13wC1IxTxrwaBfwwqhjkTFjFH+/74ziVfg+UR0zINdtXkFb+PDpP7Itv9BfipJkKbmcE5YpFcR2OWd8BKUsv7CkzrBJsCxmVD+Tmu8o0qpMJUSiK3HeEj3yQGIUO8HCoHMD2BL9lLglq1HWXVqshM5V3RquSioT95rT+SKeyqw3ZSG2m85rdD0BypaSdDUCNUy+THPN3caYazhjuS5cAGKc08/5KZevr6nx6BTS3QNPgaJFeDxnatCSaGMszS0V2BqIi+5UBAo0aysWYe3ccyDv2Mvfi9AbwsMrJ+W8Fr/NJT7UnM5/QD5KJaMeGalDi+PM+c/VpjwIJo4+oTn2pOsOk23I0JdkF0mzvelIsjOZcZU1gvQHC3ApPeRpmJAWPxrOTtf4An7TBVoa8EMqrMvGAYAY0pMN+MnE4/WfVVsMV1izPbcPIqI+MdbqijC4ErLjjPGRJyLM4zF1eK905WLX0j1vT+h3u+q7y/B+Qc8+hjv354RkeBDg==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
