apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  instances: 3

  managed:
    roles:
      - name: authentik
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-credentials
    # recovery:
    #   source: clusterBackup

  storage:
    size: 8Gi
    storageClass: longhorn-pg

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: "s3://mthomson-cnpg-backup/authentik/"
        endpointURL: "https://s3.us-west-004.backblazeb2.com"
        s3Credentials:
          accessKeyId:
            name: backblaze-secret
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: backblaze-secret
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8

  backup:
    barmanObjectStore:
      destinationPath: "s3://mthomson-cnpg-backup/authentik/"
      endpointURL: "s3.us-west-004.backblazeb2.com"
      s3Credentials:
        accessKeyId:
          name: backblaze-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backblaze-secret
          key: ACCESS_SECRET_KEY
    retentionPolicy: "30d"
