apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
  namespace: authentik
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  #immediate: true
  cluster:
    name: postgres-cluster
