---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasabi-secret
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBU2gj2h+qI727iJ6U5WUiKOFOMQQbFxOc+1SUBbdC3UURdkz07iMX/qPV8sEA8sKZHmR3vxRpscG6V8D+avHN8t/2LG5Nt1BRngMxQNTHFcpmPuuhayoQBNXMdoy1xozwKDF+P3JBGmNsbTePex3Sd0Utb45ZJZbF6Egrhm2dyh2ai6vu0bPFXr/pmCbE0gK5TkavZOuMQdUILr0OlKVxKm94QKiwCmKqAvI3QCz1UgundMjByxYS1BxN08LvDkU6WC3dw4KWVdlU0JWda2RDJC5JL/BnkknHUXfqCeb+sq6eDIWpkcMMrV50x6osqful6BmOWITwfPKfxqgOskbEjaLEo4mi7NfR1BeiRUtZsIMM/TBSK1Vyzn4qRmcikw5RtjuFrnJ2OARQZ2ENHz7xtEAwI0q6OSevIjo38CT3yaBPwX2dBgl7lE91FQ3D/6Q1IdUlv6ml9CChOLIMl6fzbvQe92ij6cnV+9Wc311626Z7CodY/aygzIOXqNHWWjVfhtLp7HBtiyHtCKBzcdg1GAH6tjH4wFL84+O4Zbd+unHXRaktJc7Lj282AeP/GQXa8wGIuf0LLXbB78ObgRR8sE8qYby91SAf45RbELvSQcFmEwnFVzPyozv8TZ+LE6tMM6hFHz9mHsBlDkxbKT7Supi8Gvomc/G3VDYOJhaHNnmKxqb7G1zjX9NuUMynpqarOgWtTmzEc24+o6bvS9SFNsP6qrg==
    ACCESS_SECRET_KEY: AgBUKU+9QZlDfvg2ufbeD9aYgstLtDGD5pq6axHS9JFA2pFoPUErnhHOSz41ODtMarUGm5o7QTnWXJ9BLFJEf1TucIzAPbN+rGP4+pIJ7fXu4g56k/yNl62gWsv4MXZFg8ehNbACfzwWOySGXB/D8wZ57cUkR+fdbnmUM2E9LK13E/ttvLz1v4MRM2N6Blk+dTC6Cl4BJ668pnJoIbdbilvfFTXWv4dmHA4aoC1RFUEQLK0X0jKpFsHcw7RMg3PoK/5mrtHOyNmkmM5TZ41pfdLM4OPripZKLiQfs75z93KvbkX0HOFWA2vTAJs8mKuKQFV0QTUUOHj8VWRRnBFH2jho697EFKy6b9uHkxG0I/oavb6biN3nFPefncvaDIm6Cntl1DjF0j6icJYNy68XA6VtQd8CFB6vChjI9S5djofVhyLIdEM//d4U1fmyXC+IOi4jUvGjf/1zXbCykzDUWwjQ7zjUAjqfCTlF/9ZBSnxiadECDLBnAn9j2oAC+CkBvt60bx0AaadcWV3j9jchLvnaqE7Jpz5P5QqQmFoQgNUe+ld2z4jUHbEMCSjG5IPwcf1QbmnmHN6ChO4P6+io85To3V79Xz32wuFNq45Bkyb6Q0lSJ9J4Y3aFevKLFYduLkx8+4uLzf/izhYAsSzq+NgH9sbuq/fWDkZHCy0sbANIGdW6BF2+VdCF80ckqRcN79MwCpdbiSOeU8it8nUsqKiOcOsIQ6oJDCMoicAH7esD21oVn+fBEOrw
  template:
    metadata:
      name: wasabi-secret
      namespace: authentik
