---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasabi-secret
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBkgc3ZZlZ243D4Q6AnWH7ySL6e4P8osJslY7/0ou0xGDqxDh4NoSmlwS9q+9EhVAHKFlmCrr0Mf5tR9lSFTGIZW0dphLvBvbWOOmKjF2afw+4IxojDOoxB72sajHkPe8nvy6Tj3Lst7hSAhklFcGQwR6nWnMWN6TWNxiaYETnStN2kKLIhir0KX/zhBFd18PkQYBrA/hT5/ITIn3kIlZhEmRjOTDumqWTviGqAoFPulgVGG684Qygfq3Kxivbg5HWp3mgUgMk2mwYbJIisSNk5lhRaTd/oYgILkfORgpkAOL2q+Xxtx1eaa/dKGl/AuEOs96LvtQ7brl9DK+N24bY2oMqLoWkj6LrDvxVU1RkBd2f0mxP/0Fn+YThcEoT6MJWQ04nzj2HOrFQUR9RmuloMUeX9tzTeNDLPq/4yFTUadAbv4fgUtsjtmUeECTDtQz1mWPJEn+KdzGUGKJ9gJU/1po76RzszwOIokknCCGdFVn133IEpgqsu3tppcbACnItZEOmh8fLIjhiEWZWf+ESnhlnCztPdMi3Dq+ahRqdkG60VAb74b9mif0oVXeTG6VJ8ktqzoQg3XxZxPTqi6PBgMPNE/WHnp8PSqGgw9u6WqWVRdvjXUGA+847d+nfoGFpTDYzwFA5QWXvAaU1dpzi0vvNy0KTInjixq6U5Wg1vOPMM4JYncODfDWcQrPOBWizgIRYdCWYoqYxXK1VBrXUkMadfXDFmXVDs
    ACCESS_SECRET_KEY: AgCMik45i62l+cZu0wNN/ZTF+aztlx8X6Z7ph6PpKyJlKG2klAMNzf+7ndZulZJO/JMhz+2FsMZ0AiBuGmcMv9ZnWeSC6pUbRnuO62mT6fYFERhPoVj7vFq76zGf5wp4y/g6w43qYzWieni8xvXCWsOPabSvSIMfl90zGkZjbtmjGMaZh60ICSgnBdXky5vjc0T+xj2Z+mUE2cqfXcuQ23l5RcPMMp9y7KUll+QrBwEhWNgRedlSEHGKUeEm3NxLE6f9MWuqdJSyalnIZ6CgDKLvPTjO+pky7y+jord6QxPTja4qcZf7cDm4FPr/9if2wxtlJYqk/Cx/+YgHm9S399g3UHkFkbHN4xS5q7NTuVmg+hs+ZHJL8cubA+aN4ZaWzlmCcW6IJn5pmM2AurZd4nr2udWS55c7rHiD+NcEEWJrt/jFwG7Ln5n7iBRHy+gmuRhtd4+wA8tSrndWhxnv6UzBOAUyW4C/kdY3VRcRhqKlpC2Y8bwswPFSR9nv+Hvb4mX1S5W3LUZG9Dl5Y4nYuVVHXN5ZxZNE8yEfFqHPwPPQW/remooi1Zsh83R16NsUYFNlp37FrXZ4sVq2IWVwHLeHDXY0LNfLxy6kMcH7za0eg8s0nyS+PIguDVaXaaV1ghTZ2ppf5gCtlOJ/eZgZ6S9wUcglSmIN36S7jcq/5WQ6Tc+e9x+Ku0olAc52fO4DiEoAfoVHat6iaEI8+NHaseuDIZ2YbHLTjkp10gl6IrR8
  template:
    metadata:
      name: wasabi-secret
      namespace: authentik
