---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasabi-secret
  namespace: authentik
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCrRc1JH4z+MHUUj4BnfnX3FuD2d+1NU5fG152VIQ9DltNPKS7PKXaCy5iXaR4O6sHxJ+wXFbDOovN8GAl884Rwbvyk3ktGk6X57OF+dLr9pTNR8Aw9hAAB9BvpINlPOJKwbFTDrmvv6yiA+pFe8ILiiRn0rVuHLyeVq6JP9qV8Xz622c8gwKUNAwpWtAcu3JN/Zc0vhHNFXgEbEJaSw79/M7AofZmxhkTr1EosBVC3TTz21HCPOOD5gKl50PmX3KobPloCl4uTA9L6gKnoMHq5U7+Z6GeCon9GVIxhiaW0vLyTkGeddTigMziMsVMfAbTDLMTrKDBXOqUC9Ntx7ekiAyJCUTmdSdqjCf1hCwOHEDmDJp7yfOOv3y5+J1jzDj/eo/oIldcPUeiQQqfn2Uy5et0UJLRq7iiXCwf/stpvfmH7RH9uV0XdQge2NYzkvJSYP/xnz63TOaIa68WktOdpW7a6eGkcWiBLDSrfNwQ0wZXNXs+FobDxZdwslawyAKuqg3sFvxa/YkVzRX3fU0xO/i3vyp4VOXqGVkSb6Oj5Z6BJa+Fasx2Ve6BTwYCkRZ4TWGdijuEHdU6pvTw4A97OcrIYqfBqntg+7zT0vfGJAnX68BgOKsRq9MH0oy9ZC8vtY70dIIAN8GmnSeTuLigyAYaU7OzQMV4GnLr8etxMETPmav7AAup8qBJAG8LmSBpzZROpEFlgsLL28Cw6gQ3tbamm2vGxNKb1
    ACCESS_SECRET_KEY: AgBWspcRj1Yg40bZxiSUaH8bTnzf1wpjxvtLO6+Bvi5wWUiy7CiWYEnEd5OlUKnYJ7OHlERWSVADP0Gc0HkJS8XqyWmKOnVXLttjUdEvV157zpigzY9hdjAhIYb+5qquArEfvP2k8KMODGA2aljtW8iQhssingYy9yTydFEKjy8Qg1fwDOMHMiQAYPWUWOsari1ze+KmSsYv8LNLx3i1YJyWVAywAw7YtqsTkWqqOiUd8KQYaV8GY60YVRupA6H6fcM1+P2/TKaIeRoainmY+28M9U7K1s2lqAqFqIksXfSXtiEz4JBsxnbFFOEx4iQ5XRb6n9LNzKKJ/knBmIhdOR7Ja/DbMmQ15GzVIIaUYBP/oczIVx9K9RlbhrDFvVifj2C7GSspVi6cscro2v4wfr0feY9RJ8P+D4koLiMb7L3ZCGuhr7NyWukGGauPHR/q4zrX2cUl3OAUCIBs5M4zPGiVpxQb4KW85ZWYKJywvfd5IW1/uv0UJkIsd5EtWx/QcabvEa0fKBqakaYndLp2wy0DkJumcQ8fwdatnYz9QfY3uaZhu80g6x0A9l99HjtgauBYR/FM5dfPgf4oiZNMZzILo+VGCrsERECJGeLvDTGVZgEtM4TD3vo7vcWF53VLbSeWIT14u4tn+bnDBKD6achVp8cjK5nz1CZQO8GjUbyp4l/DUojbHmhodQQGFqLoKlr6Y5J1vpOVXmAXdLa85BUyMb3N0HlhJhji4JDmDTaB
  template:
    metadata:
      name: wasabi-secret
      namespace: authentik
