---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_key: AgAp3wUs5nsTVthZXvlsxd4T8EEkS/LnSq9Ko4KVicnFUwBivm/TZp/7A82AaiFJs6zAJCSgOQAyUWvdTfPiwA2yvrPoN/LrcGt2JybPKj9VlUSDDRQ8ipw917t2DsRpzIuy8N8hn+dljBR93xATNlxV8X4aNdoSObpl2SK6FFwJ7cd1bWMoolIl3D9RamwnIi86AS68witfvJ6uXaVP6LyDrnrpIk1FRvHlWRVBQVk5GIfn/rX0/mqExCOWqXRVT8oMm0Uk0rjWg282QGuTLu2Jh9vg7LuNsPNOvBX5kqDSmwhebp7PV2MIUpdoLlFQYfZtqV6DyspaKx/mvEzXdyxV2+WwOuzqpf1jZibwcaCZ3gSZTMKIxNFw/tOaCo2/SizwcrbsSArXIeaW82fO0+hR6dpvZ4Tw6uvt9F2ZYpXau+Mo8v2oUcd3wgvdbevsHwPOH28snYw7T4GvDdjd0nokgwYIkHOzoC58gTSFdb+E/d+X2ACs25ZMfgNTYKm33CzB7BatUm9gTdc3xgnSNkPoux1Z/fwxzboMGAz7a6UqG0w7uJqWbZts2gLQ7cf2GKn8rYH/fExFCyoXE0MlSV3NYEaAViSFpxOXPFNyz5YQ/4ox9lDT7HYW/dCMa2wBS4341SDs4C2JRIIsppyFDIm2x9KgKATLg8+v0fgHQiBQ6eEdQpOkPVcB10/WTMwv2ig3fmc4P414BSRfcpO///+iokvMyUKjAwIEYSLUOQxvvwQD8c/s
  template:
    metadata:
      name: secret
      namespace: cert-manager
