apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 36.x 
      sourceRef:
        kind: HelmRepository
        name: traefik
  interval: 15m
  releaseName: traefik
  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        enabled: false
    ports:
      websecure:
        transport:
          respondingTimeouts:
            readTimeout: 600s
            idleTimeout: 600s
            writeTimeout: 600s
      wireguard-udp:
        port: 51822
        protocol: UDP
        expose:
          default: true

    service:
      annotations: 
        metallb.io/loadBalancerIPs: 192.168.18.200

    logs:
      access:
        enabled: true
