apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: weave-gitops.michaelthomson.dev
  namespace: weave-gitops
spec:
  endpoints:
  - dnsName: weave-gitops.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
