---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: smtpcreds-secret
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgApr8G6ZenwY8qG3KF7YQI4q+Q9dYYByYIOuYB9d6DHRfEp0ktGt6dR6b5byCCB5QN5qXMy6LMMftMsvY+dhmg8jVtLh/TbR+fFAUFfQJCklzO61uVp+yfxgzsA5A6Utp325SWo6cyLibEMicO/CutYpmMP8VkBayby74KU9leykWDwOq+4o159MAxR8EgFXmD8Ve+2ZwW+Zi4lif+EP2vDFKJyeEdzGpYLu5GIMjySsjdYG7jlGiQ9VQygqRChTcuGT5ucRlODQEy5atuteV59jzynZ092pW/CmifPHYWt2w6DwtdtUmXGLBwBjr7ZOIQaZksJOC93gFiIjx8hNE4GZTPAkCodH7yGqUx4c8G//VxJuB8UjRR1FtZTUnj/1xiZPo2VodESykpyVB699teuuvNFswxl1sQWHLaKN7D+hyOru/69FJW17UO8IFAzCBOyvQmPL6xkeZ6bbiPAvIffoMDJupFhOjolyKPrOUbZ7ZDtZa+YM+BKue42XevBImE3uWvPCt66HKTw5DzpOt5Xrpdf6Rr1RdDeJgAbbkUDv50qugW4Zrx1y92+ZNJwqQy0OsEUxKiwYQjq1YPwBYt0XLjL5ih3PR6TuRcd/qukQMKM0v6NgNZ/jW8A7l09vntuyONqib8VyO4aIBQ8aPR71wcd3SCbfH/w6m8JAbfGoOVg7BEqT82h7HiHG+3JmKQ9c7QTNaSpYX0c6baAGov/LrzK2RmJGhy+
    SMTP_USERNAME: AgDe9QtO0PGzRrboUmUpGBNmCtcfsonToGVGpB3F9J1NHY/ShVUPk4hAss0539w1mKx0dXQMB7OIXtk2IwgivjxH0DF0okO41GMvs8y0+/PBG4dd2/l5w/ITirDbCIJ99iDmqBiwAcejhc+Fz5yE2/SOrj3fFC7xh4W8IuUxLJXocSmnMMRTmlwoDunE6qm/c8neQTu9GLgvZtzGiYvCKeKgzE83jMhb80lowO3ei6ggVBEHrZc6fyAyXYXVrDx6+vYZVwcnMZB1p3dyUcUE+WvFqRHBFFrd+diJ21/eN7Nd2zSzm6M4l7h2wwc4Ww6At+UfoQZ3oGlQ6DS4iuEk+TBAw7j+yhB+Nj6Q1NVqbG+ml4GNIFVVKLu7twk3A7rA5BqJi6yCzoVMhLSLU+bXycuW8lywj73nuSxa5aqqFBmhWvpqayA5Qx6zQNFtM/KesFe+s3UEHeQjyTl5Ib2cGmN2AwyusmbHaTTH/gK03SfgHKrOndsICWitXyI6OPTZ5n60QF2HLNz4eLgwmMFInCgGwNuq9SLthPafEbYKDwFhfbYDI32kMdnUc1lXAfrs60D1pMpywpVLIj9Vpnrr81m0WbiUmf6QTmO2sTRR4CV/4w/sI8ZsoQxc8Eieg+h/5WN0qusLZpOATsZx1CPlP+p/k3ey/X3VDEZ/ZjAniDJ5h6NllF8w4avfkr1aTaXdIQxVPSzCB9ZR6u5q63qt4WEp7Z8uGCKr7H0c9uFoIkA=
  template:
    metadata:
      creationTimestamp: null
      name: smtpcreds-secret
      namespace: vaultwarden
