---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collabora-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgClEPZmgMoTFqSW3Az/pwlu1hJz3P8W4p2VA53BPXRZxn80fIRxSEWrjsBVZBGG7+/uYeYvyeeLVZF0+N68F0dm/V8DfZs3VqHNueuKmZ/ojZs/xJMRwYRt9tQ8XJVtg8duZUwnKFtpt9tpAvCDxIZBRLOZ+nbzb0fbqs+Qe5EPslYoQy3VbLHo73R8d0kqR1g7TAAhMdCBv6AhcxUrr/d3lJer96p5Dbb4842KcarsDl0JPX1xDVaJ9ZuilJiJGRiO6gba6pbAcJu21UDohknMMxZjii5sjulnw2ILlCkISdhhW8BVD1uZ9gCry0RJxNfdtH/HLAx/dyjEjBSOviDdwL6QaZ0EjeHV5ZXkv+NPXCWcdPvsHyKMYwSvYMCahtAHOOC4RBdWyj6IwfQVB3fB+RRjvxMqicffkexlxsvTrA6hfkzEqE8lSwqzgLEUtm8TpZ7IQy59L5Z7saZFO+JJkKIx5idcod+1XyYTNMS2GmGjxqQj++a9SNomkKvTQaxJLN2c16GSIQkhTBmN2e5YRNVcaVeOwkDruY+JCXF40wHKBhYxaLNIfgM36W/X9XEWj5f85xjRRsDxtDcR+HctCzrOx0ph1sy9hHQeqDm9aYEAh/jTzPYq7sP32HZseIeUPu8GEzh9kZiYo4XaF1ZGZVmdUxs0Wk3Z/wOap8vhxXPhdG821vBVuEYtlu1GpUISPiK1qzdJL1J7+QsS
    username: AgC2cyHWMSyrUQV+z61VbYUJ+ERPKRzILNLqiQefvSJFvZhDJTxI82/h/bkGeYM52EDa10LAL7cy1XEovW+l1S6Flijpco4en4zG7i94TCHK+wzNJzG0yz1d/qJN1I8ElW1pojWbPk4VxoUgvW+XVuLho+pFOQn+XksKp/Eampg1B3HIMOiUUNkB+5PbJU0okfv60SOTp/gqLxP1HnrVpCQCOqnYbN3gtwe1R7kdWOm1KzuRcP7nyL7mxMEPxaEislhNdRPIIw2ky+gr4EgWzBzpOJmK8qt4TYmBB+cj57RzSWY0G2VswR5DrMZJ4zLjPhRxQygoIdESj3ktsDaKt1Kn64kfifESIHGGTBYa8C9VAlpKslRnQegVDgIQ0xXk3wniibJufXW/5xW8WINz57G344MLkn1A/7N3iJK+uGG0HNoQpGzyQJZDZVfkZ8KAOfO7gbXY5josT4IFnwJMWT1LdPTPd6n/Qpl3WRpoxXIh0Ksmd+z//Wrwq320bPpbhvt0xKhEGLD3IRQGDEn/rDEl9ik8uqj/xA1ZNbGPF9nJhw0S6B7ihLfMGCq+WE3CoAXXcrRe5haYofDcjBpEY1dPXKHaufmuEdHWqwARGdRtV+u6oRd7sg3OfvNKlAX2EBGR+oy1I/gi9bq/TjplShciv2Sy0wN6jhtlbnIPqhDXQV1KZVh8kGSNq0sQnu2PviRvucJ44Q==
  template:
    metadata:
      name: collabora-secret
      namespace: nextcloud
