---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: collabora-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgAIODKH6t+Qk21sOFSK7ZTHEAZ1NrEpq4ZvnyVi63jvAsB5WbYCSf5PRpxgI3NINScVm0DxD/GMzZ4u5YEZQiLnReeEm0pEyp7cfk9UMANe1OdimtvH6TwT2XoFpxONL0/fcwoZgc79s6lMmctKWgis3wRG+BOy8ciAArutCh+2mQWZLQsYcyVlnekjgOXmzvFOjLfiuPFojTKYZXq4jNUXLqlD2Cb49d8w0Wl+bh4YbZ9JH2zgsh5659ArmnfYCbHCg9VUKL8xrAvio2NAhI1ZjfAR9vGTWECRHhzs3q6rSMgoWwORN/yDFIqqsnl6KQBCLyVjgVeTYBFdepR3hhyGYXKTmDuKljYYX1fyApn+wD3qAiXdjsc9lQcOkkMp8Z+5cxPV5CBVeqd4jXKe7WHAhIwY7/th6ECl+GbJBETs/npnGwn+zJLh3EakdpvJm4KV5yLOwMrgxVACcRRs+0QACYkHgs07gSEdSOTSZGlq0RH5azyjORtzrqKnFX2Y1EdKtK3dr/t+ohx2SaprnyI3C8U0GjoiP/bjckSgnLL2hTF8qzu7C9MWm2WmzsvjH93xgGZLTLlUtpzc2XUqsUXg7uHgpkW0l/nPRCtlUvXkolosqAg/iKFMM28oEIA4+lS/zkqPibmpelqxzpTD2D79OczGiHaxIHavzWXsDtkN0q2N9aF0ote+hagLIA6wnwX0go9OcnItBQ1/K1gd
    username: AgAlC0LXSdJHOVewvm1lLBSgKHnrv3ljh2dQZiXDlUUDDLJFnfukOTB7OhD+E5C1ASxK9QQPUiKlAJenYATGla+G/0IJY+BqcbZloQfWQJbtRAAon25+y4ueAaz0hFMQ3Jq7K1U5MxeIaOAm7SK2xri9vH9VD5EhaYqQgngeMxyz0TaZBIx2/4vVWIYyAn2N8S5oFtLmGwU7ooTAAWFmuxzXeNtSGIyDVWXompH4CS4Fj3Wj0/LkvcyqzSKK8rCn+KNzQxZAxoZrHICI5m/20ih5+jjFFQw0Ot3IgC2qINk15b85tvl2UKaRVVlwKuUQtcnY7fA1sD2OOaP2s3XGzwN80EKVrBEN4ptGUsWsbzM+hMTaab75+xsIEXgjEVYF/xni2GdRQBrpksvfGIdiyQigyzinrZN6ZkJu02Me8P8ayReAbUgi+fvpXQgIblzbbr97APXq1DPn/w2PXcGdWJ5R3WP7I98DVjTsQQTUB94Re740cubJyJjXPWl3mm45J06D76BxLpCQEUJP4dOZoTf0dFjdStOStphalLcY2tbsX3ZZdW0wZYcm69/6J2aP5WOmZEvYyCjPZViDIY8WXixlWEPJfz1SHs5GQ9ldCULJZhLIXSfM98r0f1kmaQFy09voLp/KvU9+lQ1eSxqlVZksA3UzgnQHJ+kxKnQmWC03UcGikJ9HRTrqlFYquho28JiPhBk/sQ==
  template:
    metadata:
      name: collabora-secret
      namespace: nextcloud
