---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBGQkokYTn4qYzR1snkBbJaBsth35a2Sda3zyIzWiC3+wQBxX0OWf6Rw3Tef6x2bS8SsDJfCStFVErG+DI+oHM43eJCdOqW4TlFf+Z0t3Tq36jKLFovTzfPRuEIeC16C1y7UFOwnUQ26G1GPli2DsDK6H4P0EAkUNBnLTEmUMHXEHbKHJakXDOk94cXjHr+uGn/kQB3G398TMEeuuL2WEIK7zrrsHg7zgPEZcSB5e+sMpFpClGWMGZ4MsStaERSrpY07FJplb11Y0y3OJ/m1YsRGA4hfR0PrQ5K1YKeRD6to2wsk9kA3Vd5IcpuMr4S1HMGb6egkrqv67EM5eOatpbm7p1sHdzZElYI+Dx18/O8Pkv4CyrMYlQK6L03hop5orVaVh9aW549dHJJ0/VJP15rNaHiir6BCLzSfK0TZ8gINt7Q6uOo7hh36gBnOfUbmOw6MsmOHj+SdVbrHxNKTHCF3/6wa97RHnOImoG8yYoAjIjLL44C4jfyk3AltwRlbGN8ULzk0/2FKaxhk/QYF8a+CRuBvEDm+Vl4JmBKUdBMF2meY3slATr2qCBbvjzeSUVmhY6WRBBBO2S0aSwdGqyIDnJoJk/VOJuMdFBWuOrRhfSljs1NZIPE74Mich41Cef3zu0ixykqBR/2rt4SaPuZ8Pyom3muBWb9u/+p9lEwoOQ+Rg5aLfrNNOY7nPHt443EQiwJ13bSXCFY3DaWLJwBW+rHAjDQenvC
  template:
    metadata:
      name: nextcloud-redis-secret
      namespace: nextcloud
