---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-redis-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBmK2klStJHOx1Oi5spwxTAIPsGlRE/En4pSItTUFRBNlEcPLWq9b6GnOAd9Xek+mx+MMKveKgmr29uM0FEbPD0m706/X6fEi8qfe/adJweFrgDAjlIaZ+Ve1EiG3grDwrSlpLjG8CXpH6lVS0HDUp5b1+U6JxpkPRTz7SDzcpfT4PSr920QPY78vekJSm/rg/R/CzYS+db3XPhNNVZk/su72ATIawTaUT4foux0LXEYb+GQNWEu3Kb83I7JxLfcHhsJ7zMG/EzyB5ACHJ0DKgDi3JNe0NRQ2woOYxyZn/3SGyDiqzJfLFw7WeJVuvYdYDGEKqV5g/nkUcVjmB3NzDsH/UrK2YGhEiyMCwmh9B67MsrYwAMLJp+f8iz2mqIkyZDQIDr6gHZXuxEMEwetICm8FzQy5PC1n7xlaeIZBWobC91EJYK3LTTluVYww8QU7qZdGhrtnFph2XaJE2EkRhJLfOLZLRXnjCbQnpjhZV+WBlWkGZCOdM1klb/wLiprklrC1dcP5LcrR8dpXt1yQ03wtxDJzQ/QTGeMcxALGj8bGo/aO/mikuJy48Re2NkRjuZwsSOFxJZUpT3gtXt9tQeBzXAODoZW/bpvDb/XffJdAoDbdHh9DBjrQP24qWF6AK+i6YUC/JttTxS1+23IF8cz22NGMcEmE4HPZlPVpsD4rJbShbT0UoJU524Ebc7H6grOgvMfH9KeGhkxQmXJhAccpisiyhkN29P
  template:
    metadata:
      name: nextcloud-redis-secret
      namespace: nextcloud
