---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCf3UGFX5H6PRnj6jn4u3pTB5jv2syC/4F8HCnQCfFNgxFIuJ4PeEa8kOPCqvfATameeJ8M+O4AaSCV9bxe7wF/8LWtMvH7ivEWZzhTjhbQ5hAYjcN5IkP9vC7vMnA8Och6csAg0jwATx6wsyDzBDVWrc9OEDpxT0a76P7K/c16keHsYyQiKFq6SsPybMw8EvpVtYIoNW0/xaWl23PvIY5VTk2L7+9ESL2oLv0n+GQosC+rNuRPKTFBq5cMM75jRiRRj8UVk9QwISpMUCHZwiE6Wi5Qx5w2pogvG9oXcpgdtxytvHg/E7ocY2zbAPXqayijFoUf7GyYFGn28A94/+2pxQA2AM5CU9IgQXJIG/Mi8i8p9d/O7vfpUEpt21MC5pk8pR1RaM9lyDcPwn4ClD/5IoqKWcWcKL/zjOTp1tkVEBEjTNZHfGh9RCc+0R2jZK2UIC8QfptZPO3nhy19y0QNPoO8I7cenUe/X4IPsDchMKpbvWRxxbcr0Z68V36DpURhQBn+oyV7Zih7trtFP0J0Qz+red83JehuLHc7FlK5TW+/EV9RwLcwHXO9zsnBivmcitVMQglPC58PZ+DGCgq65rsQfrutWlYT9vKJabzf/L1ggEo/LCKd4P0FDGZArjyFh78ELH+TmYFtwIU+EQwgTjtIijrnVFReMMh/TTXZ3xgZJLOzgJ5cGbMhCE0Qd5UeEtat+Ld9qiKMV7fQ3oeB4XV9FjBg/2pc
    username: AgCXJAIKANVfxOcbYwMINU5HNY5X+j0bJztCvkTbGDYAsM0DigHNKil0SGlgSn5MJeftip9ii3e3lOTX97pe+36FD/kXPlAbzN/3Ydq5Q46KxgzHtrrRc111qb3oWyCY/s9rWtcLFKPuRTAjSG1FFxQ8/N5MDmAkAL3vOS07InxCUKoXLqB7jT/QLD36Sboge9PfR2h+btCIlihNzsdDteCP7YmStAnJPbkb1Qfr76olh0G5pJxz/DlOaCkwW8/tUdoAp6Bz2fuhiEkMx9Gy7jPVDJTO6gvWzMnQZcgq7zQ959wtqpKOEiXi8Kd56qdgnwYA/an3cgUfPbiwhZ1lmqlzegdGUICRrUdQPBL9gLxLIpHapnjsS79VxidvplB2vJ+Fmc7nWvpLVS11MTnLAdwpeQHXZ0zrYXAqp6jbE989WQxdnOTIYMPIij1kVxmJQNUmpLy3HFuEiJOpMfIwbyHCWuKA7/TF9FBSSVr801802wZvvBacWsxLMIkmwt0vA4QY3cPiwKhs04GrcbTjXh5ZUpDZ/lJjTRiJ+PTHm5pbFUFGmq9ZNzci934ng7KWynoodZpjRPDozukTyVo1dNLlj7tocmJO4s/fhJiNVp8PZLjjytAH2rhjAB0g8+ZDriUFobA3Hlw/Gp1OuauGdWysygTxPpvlo4UbV0780rVGJB3AvLnVauwIZUZXNcTsMhrt7COir2QTPPQ=
  template:
    metadata:
      name: postgres-secret
      namespace: nextcloud
