---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: nextcloud
spec:
  encryptedData:
    password: AgC6nIQRTGuRsAOzWTI1C4pwpKqHHU5NBssywiqCrqQVuuQVDoF9MgoNhgwAOm4NSkpn8gkJudXV8QrvHHh3WQBvONPNAG+vOphb56qWhME7eSD3QIe6INQ6azqgTctDzwx9Opq7yKRm71lP3b/CeNOaJuBFPV6EKdUcMUrte1bzDwI9G/NwdZwz18ixwBLuCxWHEGfwjjcUFc4yTPiitTKT99AZFV50QNCObCOsA1By5KVQ4Jsrkdz9bJQQzevOzHZ1f6jVMQiWQTrkgDv8L/lzdje3k5DqUOCXX3iNrtDL5U8dXWZd9A35i69e8AubnQQDq5t/jdzEOcX2/V5cn4bbxdcxlNyY/+/+kCwNcHC7zQdoZzwQKtjREkNVlBBbMH5/wX1udxtcwK5G5vJ9znxmGEAuU4+MtvjGaniNGUwgzV/dlCzWK0WHbO/DI2plGYu4T5m9vVvjorETGBKnzc4/VOXnvYZkTMRgBhy3GQPA1ycIhZ2FMMmquPTDXFbz19kK0uci6rattRISUXZ/c8o0pSfg7jBylFijd3GSTNwa4xV7Fwc7BX+Xt/At7HWcPi35ForYHd46+zgMy3pQ5OkE8ho2CTJcykItzFYFZGPVSYX7SEVmM84Ko66yHVmnBvgfD/bL11q8gvxtXvX6AHGUmrg6pfPtU+V1ViruwwxYpq+fbEDYTpct2lrv1zH0DJHys2IkpmKWkWPtZhz+TIxeyhjwDbhFjK2N
    username: AgAKWzxs2E+IoJXe9crxpyHGYxMpB4rNRvEPw2pV8s0oUhhDxl5qEu97huP22VsbtK6zA+BKTCwPEPHrEkGhmfjNVM46lTWf5J/NBNbgl13AeYAQ6N+P8ir/O6w3yHc0FgB6Yt9ZiaR9zxuOV09osC5yf0fpUe2RdSi6WojYHkyvCdjjkmX7bDBJ8DjsCSRHaGMOYR/LnxItUD96fIjv+HIwCsqxadPG6Mg6q2TCRDzcEi/4APUoQxHNg0Y2wWuU06RyD3vadboJYvexQM3zBdovPvhYg2L76NNx69Y4g2zd+gDc09Nw01D/ssVBuKZSOQ0+eFoPT2JyIxSjXDhaXoQsfrk092JOXE6a7PlxwhUvLjNfAmb8imW3zgjF6bi4X5289RxM2ymPQ8k9hFGfIUT9Q+WFG2nPK9p6AgIXZ+meTFgBh1hX3OS+jbGZ4DA1wIELdzdt5Y/94xeVCYOx5v1jsCAmOPyy+aY3zF9JEuDRcE7jV4Vdc75LSflfVDepGvkCHl2Zv7IIlSjAKUtxIC2yXzT9bE4Ja/t5m1g7qY1k9Rg4pq56mCk0QfCrNZGQy5EmbO/U+Up8AqulYNMtbBwU6dptdysu8PXACZuZy6Z7+uSSiYsgslfVreutVeMMvGEygDufnpMe4QhXHG7CNJWccVHp4JbrW6xarqfzOAa0cMVgmZIN51HVcRbu0q0Z87avEw8KGw3Nnnc=
  template:
    metadata:
      name: postgres-secret
      namespace: nextcloud
