kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: bookstack-secret
  namespace: bookstack
  creationTimestamp:
spec:
  template:
    metadata:
      name: bookstack-secret
      namespace: bookstack
      creationTimestamp:
  encryptedData:
    DB_PASS: AgArYCwRMaba1yKKJMRWZ0Ggr4ioZWPt7Z3PBDJhVl3WSKy6Hc3xhNTChcSbWAwAw5csP/mTbNiUU6/BYU5cCx0cbQ9jGoyVBDJ8bIboQHdYwgJ8JAC6jp4nN/o9+Se6ys2HrzgzsHnWTDxWaIZIjguAodQePhGQOOMCub+GnU5AvGwJfZLa0E+APanL/9cLzpMd6dCs7RZEQWvbOm5VBysAknhtTcfFdex2lbEoLRrJoNK0ZS6kImPQfJTyESs5O9dOBpg4okXD11UG2dpe0kotuXTMABL4nBumncR8kAmMLT8luB4OsV9h6rou7SDFvpRCxc6W6ZSKlgXp6rq6rhCh03ojMIz51BiDzDnYY5TjtI38S+J+OXZgvaZc8rlCFUf4GyGvcdn6r468MxDhADkx7KDgymVeSmoEPiq7HLg5yJZZS3CEKCFlgaj712hrESh/RLMOQxBNB3iv0dRXfVImUuIEA1vsd3g9bK9zQtgyjoNoJ+vfOY2wiOcciXA9GlYn08dyFElTlHpjJ0c7KM7ghPBoQv4iyjd9X3+w/85U69muFylLx8lirZ/vN61vHd5BnbxBCS1If0Ya6vfuYwGIofQAMJqwHbwIgZaCx6ZxsBc/L5Td1zPd9ObOf9JeN5VFS8E4Qj4qhqyPRgnDX6dxNKek2ShjS5SIJv+J2lc2dx/y1RWT9C1iJgkLAMfZtApoYCfUroRSjJWHgdFNtT4w8soC
    DB_USER: AgAe41Zf+w5i5NXOM3TM+lLX7DCsFBM8uNTyDhWyJBkKjG6PuDI7CiP7ieV61anTIMEAckm05i53rdy4tpk136U5L+EpP+HP5W/DP2AVnHL0vaGAmaUNMyfy+IpuSenLXxyeM/v2io0C9vtxnJR7m6lYfdCn9bq3e9n0PoC5PG2ErEtjzQq0GhO6SPEhdtuamr4A0ouXI9O+iKHimphQ1OU5fEtUZRy4kDQ23nbp4fNg09tlmupOF44ywmrq+c2P4aZEDXolDrd94JaGcnb0/IOjeaFVi42xC5jwt5LIyWHocOCYzkCE9l9wmRaorQz+pd/BLewoBJ43bjmqbyksdQ9plGp/0V6r2jeLwQP3eRjE0gLTCTs4QQ/Q8djqLKwNFfewOhbNANv8r9LiQnnpxJ0cVrFHZyoPkkt8vJgE3MS8luj8CdqgMtf1XEu9vLLVnlUh+Tcv7zJa0qt14nILzbO6BHln2VhZDdapBVSKAQz0B90Gohs6LCE71p+mdsTMin5YZ5/ml3/sDTOnrrugxwscw0DP7KwvECNzo948SclF75VzTx69u/mscBBcDiYiIbdYhLjlu9krF4Mf8Mh8UZJ4vvM4ivgBLp9zf9s4O5hUngG5bQlrLX4NIHURCHTQ8WkRhqgWGhvU37/6SxasPUbTQYlcKKXG+PAp5qJkFfaz0qqHP2IYHG2t4rwGMl5udf3OHflIORY8uq4=
