apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
  namespace: bookstack
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
