apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-web
  template:
    metadata:
      labels:
        app: karakeep-web
    spec:
      containers:
        - name: web
          image: ghcr.io/karakeep-app/karakeep:release
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_URL
              value: https://karakeep.michaelthomson.dev
            - name: MEILI_ADDR
              value: http://meilisearch:7700
            - name: BROWSER_WEB_URL
              value: http://chrome:9222
            - name: DATA_DIR
              value: /data
            - name: DISABLE_SIGNUPS
              value: "false"
          volumeMounts:
            - mountPath: /data
              name: data
          envFrom:
            - secretRef:
                name: karakeep-secrets
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
