apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chartRef:
    kind: OCIRepository
    name: keycloak
  interval: 15m
  releaseName: keycloak
  values:
    proxy: edge
    production: true
    resources:
      limits:
        cpu: 2000m
        ephemeral-storage: 2Gi
        memory: 2Gi
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hostname: keycloak.michaelthomson.dev
      tls: true
      extraTls:
        - hosts:
            - keycloak.michaelthomson.dev
          secretName: letsencrypt-wildcard-cert-michaelthomson.dev
