---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-url
  namespace: todo
spec:
  encryptedData:
    DATABASE_URL: AgBxll7k7MBVaFaqaW5RS01tt+KDAOhyyei4ap5cvuQK/M0j08nY4Hu6hrKN+4I2Lm6wqR8pOYcM622QVp/5onL2II17ouFZKQX3JXDZB7r6bJJgkm3fzR4sIULXNc6VWhgS8DaYHI3ZmtMACqLK11/lAzdyXfq7ja8VxTpcE/jGe/OSqzxkObbJqt9goIIkpr7Hlwy+tzC36R2XY+3ruQQQdNk7QRbwiZiRDUCmQbRjE/0Mrq0WNevdy06KoM4EnpQrligKO6Ow6eRbZktHDZM4HOUecG4RQcB7/t9dnkCEKnIp5fAh7U95RW9lmDE0zCLAEtliJVDzIZTi/4vDuBgwbwI4HE7luK8N9RsJVYZt8USRe/vLp3fnmH+1L0lxtV76EORhsQj3sGq6JPTJ3UKcYudhhhJv1Yh0ZHt2fyNRlVpra6hj0qjNa7AHijqcp8gpxjOE8/aXQOC4v0i9vYeGUTaYNXfekGqnbQqUaEdLUsskaCPPuQYt8s3kgGv1L50pzMGJvX6ZiI97fkf4UYxrHf6vprSyfAcwd1iX3Vv9kC2LMsD7q+pXZCuh11W4CBp0fEYFslMyTCQj1/S8N0TfsspTlou+H1mrPHR1pJri0i8jOoEFqJcl3qu0l3aKY7sbccB8W/a6hRuBW98apWqxPoyHnfCQb9KzfTQ52p/V+jDVOFEFfU4PvKh3R4WxrjxeYNQdVsarqScN7IRSP6w+y5Am4Pv1RDKBomVKgXaIZCFRrkKpyz1Y9MfSUcfPnOJLyAmyhxLyBq4ZtNkypqUTo1Zxnw==
  template:
    metadata:
      creationTimestamp: null
      name: database-url
      namespace: todo
