---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-url
  namespace: todo
spec:
  encryptedData:
    DATABASE_URL: AgBgS5ia5yF0eTcAJypY/Ca3fDM3ya9+JPQ6bXHk/WhIVhoWxq/yp5rhlt+d/nyYfk2SPhCeBz1+CX2/kedage/kXDnWVcOkBKqVggb0dLGNS26i9mZImq3CVCOlvTUv1+IlQwkkS+MMrHbMRiFDJNZNJwnVW1ibXvyKYXCOnzxQdtkL/eB2urko54Lf9YTDmEYRo+23LXZOocDA3KsUV2ieh95AVD2LUwyFo64NfeD3+U24CwWzj6LXnmHZNhn+e4sP2Q3fUjyWYiiO9qbbmTi+fgGKR1wUNlaWxbzyBSa/UBe1NPdjAVMDjFPuJncM8oyhhoCvzBRLWYgysVAIZhPtJtiTNkKvWdxjhyqaTMRXOgZhk/z0j5LvLw9eXuXFuZLSTSwzLWKdCw5fERY8kd/WNXI31Pz9ODRRJwzonojYJ07CwowxS+b6oecvuzmo9vOE4i1Ghs2uukrVN/t9d5phX0VBrsh4S1sKOrMfQpkgABZmKt8CctU34t+C+rAY2GNvig0URcXnJW1ZKxylp0cGaEg9SeH5UdvRAFdkyyf6VTE/+uG+6qFjGTqcRcXdfY/wBgoOpq9y4wka+w4lkvJPaiuDW+kkR4+I1Q92D0x+1o/nSBnGjmMS8qMxe7039awGXGbyaGcjdFw6iBUbCkAiSTEa2Ms6ksgl6Tfs1hiACAO1pkNWrym+mYDXHYqwRnMJ6fo7BFEaOzpeXtDWHif08imkfANlZfuKgXHiahhqQP1Hp1DHhpouSPLzfxlPvKBy/nHnHsG7Q1XGRQxTFaAFqzE=
  template:
    metadata:
      creationTimestamp: null
      name: database-url
      namespace: todo
