apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: todo.michaelthomson.dev
  namespace: todo
spec:
  endpoints:
  - dnsName: todo.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
