apiVersion: v1
data:
    cloudflare_api_key: ENC[AES256_GCM,data:KNFMTvtHi0py+wisSr4dMA0u1MoIuckMZ0nBL2TmX0AqRv8D9BusV/cF736fymIVw8+fZg==,iv:dgvMAjl4jSVPkSUdvXhL9Ug6NCpB5ZkL2WWXQQAyB7A=,tag:otKwcgUF/asg7eKBexN1gw==,type:str]
kind: Secret
metadata:
    name: secret
    namespace: external-dns
sops:
    age:
        - recipient: age1s0206tnfaaw849x5xmt95axgu8qhxzlu5ywrwz09tpt8lwpx858q089nq9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZE8rQy96d1paMi9NZlY1
            bysrUmNQcFJBM0FSZVAvYXRaWEVwU2dqN2tzCmZOemZ3N2FYUkdwS0E3a1dCR3Y2
            anlVcnNJY1JMeVErNXRLcE5SUXJncTQKLS0tIGxZQlU1VTZ5R0ltZldCdEZwSXpC
            dDlYNjAxa3FHaVFrZUhOMWJGWnQ0NlEKtsmpOJ8OEYGqquRnT3bm2MFfjd/AKjyH
            lLQfpxPol6AIsbVxfJm5GexGI2WQ8lqYdwA8ada0rqzBkjQ6DttE/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T20:36:08Z"
    mac: ENC[AES256_GCM,data:zyTYwIhNeBPCQCX/cNh/j3yXtftJixu/vbJnDmtQ80qQwLMUnVT6rihvsu1+19q7323YYbha5UMg0HLXcLYUvTlnmQhn708KwY2NPwVnmJpCQWXbaJ89mqJPk8Jn1EuqaLH/x4NZn7+Aj0JOK404SscoXTHLJ6SEGPLZIEefOUM=,iv:ztDN5OBcPCCy6neAlJMhCz0gLAAH5mO+fypBwuaNUaw=,tag:GG3j3kQYt7xaSAu8aDQ9AA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
