---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgBcFuEUvcqzmx2YW+q8RgVHDvTrJnfWOoCY1R0oSCSILu6tliOL3ntbS0wyPHvd7j0+shTIJwJzabYchhLg9iesYHtwoWbs8mRpMW5gU0jqMHFSjMVyNciqx1PgZcKD12/TPtgc7IofQVbQAf/z5gni2MGMnvB+5gvGAnPhc3iBpZAzmc3ja20dzm1b3RQjya3duhfsUSlr+zJmbfxkDtaHJ/ldy5kaVYPjT+/JHGh0l+lD9z8M7UiYH3tEUiXjwEudvM2zVVgdQsa0kAPXBRAJr0u7ZpqXr+zod8QzBg2zj8cSBNJoXIp6ckPOi1wUGDFA4b18CwHSL5PftfMTdGs0CGGxND/KwPwDWtFiD1wnIS0yKrQ0Akz4RN89zMco+DlmrEc+FHdUQghMaLWs7gfGFLPVND2pP4cstZHAD/NtMct1NSvpUfdBGnW3fChTZ8Yeb7gnDE27CkN3aGEBZvasW9717wO+FhlgK3RPBtft5+/wKEAJYGhQV+7RPhrVDUBR3OrKZbPNtgIqYTxmWBA4yvJPieTEy16IAO9ym5fEyN05SREwHA157z5zEvqOSl1dG1olbfwFsp89H0FvjCz2rMfElL5C84+dYagGOL9g89ZmNT37LO/+LIMfA9jPzDbAFFoN8OftykDV+HLdXKMnpAXYGwsJfeGrQJDEX9xvompgcRqqrJSDqL6dhRHxcBzYwdDozwiXEZutJi5QQUYjBVFblNmF+7kjQzOxrwvz2HNKlA2h
  template:
    metadata:
      name: secret
      namespace: external-dns
