---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgDB/8qYE4xI1LOJyJ73afBphwIazvJFS6JPWzC+4R7D/J83Rc14udHVf1bLr8bbkGfXBs9FOis6kVu480JFoNnsXZLdTxViwj573l9GgfOQugCFqn+R8tqpgyzhqpMCYrxJHifn1VZw7a95XJ494tYA7tAO+45SBBXjCVrXO/ZF4gpQpk0yyW6tnV/2cna678dG9ZoL+W7zVlYZ72RrZoGyHTjEUnadmCCR0cPJA0Pd7zho3QLczrnGe2WFRK5TbxaVerr9yPQjx18H2J489UePd0C2OeDkMorev8OxxdA+Wvq8AVpokMoOGgQ+qJ9eDdNDrJjJKi2Vs/FsT3q5B5iwuGwGSITtz3kk/POnnfU+IzzGEYUns5rgC1TrcO49Xk6W7d7ft5HUi0wdWLaeveox/jkIcM15QvXJQuf4RfphNoeQ1gp59ngRh2Oij2vlU/HZ+2eSHU4zMxC+LY9/JIXBytrPOfjvNehLQigeZQ4VQCcnzqqUEi1t8ptwqeFwhG+rWCJlNK5HZoS7p5gw5O+t55IL5bStaP/9teoMoOwyRgsBKz6Jclg0h1dF+UxEf3xsFxV/I4dEvFkz6e2jXtD823/uVG6p06LN2YsdK+2c1dey9JeYfHltha8p7+JWVaKMYjncWLwpIrNpjB+xljUCtzY7S7AKxp4IvGaeVDq1tKa/zqK9/c37/Fxi5bMgTcynX/xxU2bRuDLvHFA52yCwBKLHgE3TPJAS5/M9J4/iTplmLFl6
  template:
    metadata:
      name: secret
      namespace: external-dns
