apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: actual.michaelthomson.dev
  namespace: actual
spec:
  endpoints:
  - dnsName: actual.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
