apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: actual
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
