apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      version: 10.x
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: gitea
  values:
    global:
      storageClass: longhorn

    replicaCount: 1

    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: gitea.michaelthomson.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.michaelthomson.dev
          secretName: letsencrypt-wildcard-cert-michaelthomson.dev

    deployment:
      env:
        - name: GITEA__webhook__ALLOWED_HOST_LIST
          value: external,loopback,private

    persistence:
      claimName: gitea-shared-storage
      size: 10Gi
      storageClass: longhorn

    gitea:
      admin:
        existingSecret: gitea-admin-secret
        email: "gitea@michaelthomson.dev"

    redis-cluster:
      enabled: false
      usePassword: false
      cluster:
        nodes: 3 # default: 6
        replicas: 0 # default: 1

    postgresql-ha:
      enabled: false

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            password: gitea
            database: gitea
            username: gitea
          service:
            ports:
              postgresql: 5432
      primary:
        persistence:
          size: 10Gi
