apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      version: 10.x
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: gitea
  values:
    global:
      storageClass: longhorn

    replicaCount: 1

    service:
      ssh:
        type: LoadBalancer
        port: 2222
        clusterIP:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 192.168.2.248

    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: gitea.michaelthomson.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.michaelthomson.dev
          secretName: letsencrypt-wildcard-cert-michaelthomson.dev

    persistence:
      claimName: gitea-shared-storage
      size: 10Gi
      storageClass: longhorn

    gitea:
      config:
        server:
          SSH_PORT: 2222
        service:
          DISABLE_REGISTRATION: true
        webhook:
          ALLOWED_HOST_LIST: external,loopback,private
        mailer:
          ENABLED: true
          FROM: gitea@michaelthomson.dev
          PROTOCOL: smtps
          SMTP_ADDR: mail.michaelthomson.dev
          SMTP_PORT: 465
          USER: gitea@michaelthomson.dev
      admin:
        existingSecret: gitea-admin-secret
        email: "gitea@michaelthomson.dev"
      additionalConfigSources:
        - secret:
            secretName: gitea-mailer-config-secret

    redis-cluster:
      enabled: false

    postgresql-ha:
      enabled: false

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            password: gitea
            database: gitea
            username: gitea
          service:
            ports:
              postgresql: 5432
      primary:
        persistence:
          size: 10Gi
