apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeName: patrick
      containers:
      - name: homeassistant
        image: lscr.io/linuxserver/homeassistant:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: homeassistant-config
            optional: false
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
          hostPort: 8123
        volumeMounts:
        - name: config
          mountPath: /config
        - name: dev-serial
          mountPath: /dev/serial
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
        hostNetwork: true
      - name: whisper
        image: lscr.io/linuxserver/faster-whisper:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: whisper-config
            optional: false
        ports:
        - containerPort: 10300
      - name: piper
        image: lscr.io/linuxserver/piper:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: piper-config
            optional: false
        ports:
        - containerPort: 10200
      - name: openwakeword
        image: rhasspy/wyoming-openwakeword
        imagePullPolicy: Always
        ports:
        - containerPort: 10400
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config
      - name: dev-serial
        hostPath:
          path: /dev/serial
