apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-wireguard-config
  namespace: media
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
