{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "sabnzbd-wireguard-config-secret",
    "namespace": "media",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "sabnzbd-wireguard-config-secret",
        "namespace": "media",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "wg0.conf": "AgCAvX+snOxoUGSnPc7Cud8Do/uoNTOoXVrW3D07VX6RcMBHp2Z765q2PKWCAPTKZmhfppurfIxakEvZlv/7u/3z2b6pu5Gss8zfAQwVVKdD1TxRAkHwBvSH0MbhMJ6Z/PORzJ9U9LLBx6EJnftARu3Oir14V4BuShLdQHlukXhi5Lwo8KzV3nCkTjDEnknoYRzOFhtPRTOivjI3voJKNY/sJSNuUigE4IZ8rFWG64pnSo+lKaAKJK3fduYRIPV3npRr+kOCsSlnjRPEALOFzt+wdP1LS6U3GjaoEKNy/O0W0cnSPfVMHD5NfiBh6EiaI/Nd2jo0Wy0q0/CjSQNWtjPOA0eaMB1jIeareDBUOjM+Yje7AkvMx57pzFTiadxcw6Rftb7kAQu7zSNUl3xknvMSPN/la1+a71nMoAvZKr3bSc6nQIDqqnRQ410kqLSdy6SxdJalwSTeFnpI0l3QY99vgVmwriBGTYnNr9bCtR/Zku+YYmyFO6vI9BC7ZzHj/vkkG6Tiyg7MgHgqh+lkLucaIy6acUzytAsROAPj7pLt2aHitRxQfzDXQ+dVL01A4kvrq7OGVoRq+R1Rm+I8HaXEFBT76GdaVDcjCGEJr1K1Wy61SvdnuDZfHT01KL9kJg8069FKtUtanEM9vb6izOOj1EuZlxl2Ue9DmFMt3ewAJzW4V4C+6W2GJVwwASux2RvRwReZZDg2+rJFSCBDev6ho7eBtYu+avA7uyDgm8wQrODW35/pB/VNuDu8tLeA14U+ahnAKbf0hk6X6eH9mzJkTICGAXwDXYZ6gSU+7FBIy32mvYS9UO9tl5jeiOLQnRtYLprxIRrSTsL2w6DfFXlapFQZEP8eKh6kS76TkXdfzxPwEok3ZV1dzquLyd8FOtxyYQaQgnJDD+eqsZRfPzxXWU0x536n3+iShxfj9+SG8tjfD4caOtKjKzNx+vH4d310AxdMBFZeS8sMgLaWVkRWXU0tAJ8RptvQgSPNaVGnd/gb4xEqmAJoFoHy/zqVNL1xxE/19ycjBzcw/Kn0CVanC9AfJN87KE8uxzoC9TV7kQKhZiE+PHLAbFeRWqA/OcgDC3PJzufcBXN9hMminn0jGdSJdwgIOoxPuI0TZ3nKJh0qVvqBh3SG7XvtoBqxSeCiSAn/9W/mJK446cxGVCs4v7bvPng6"
    }
  }
}
