apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roundcubemail-www-pvc
  namespace: roundcube
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
