---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasabi-secret
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBlssYJLBzw80VTVtTC5UrYQOyF/c48FTpsVpUA/oSZQJJUtZuCNIEdTNO7pW3bP9ie/TlJDkm+3vF0DnDm+3hzB9Q7Knciep8sslMGNVOBTfBuwIyENRmoRWlHOX9MjHKS3Yuq4Xqfy//IYvjsp2dEN1DyR/giGHq4FiTmnUdx/kJD+wioXvLg20ZePDIHv8Ybt/Fi1aGLuJKhlWZ2UhN02mDICF43oXCIPHJr/VWqyF1XCt9aRjBXfzX1Ge/68rR+zC9OuNQSuugCWIQ1wMoTOWmNfFY9P74FrAM2OkPtuZJUaqNsRkIm78+MT38ZRAmM6F8/sDzzkqCJSoiDu4p6w354vKFMk78X9ls43cgXWSHQP3RMzvT3FPduODTyU3PAMXcaAHBG8HxqNJKfRmWOVWrHlLRO2EV3fhykJYHXwhNn3zAKHUDBUJezX8go7Rg5P9Fb+xagD6CedSRONwy90KARhLjr1FRqm93q3kXTAmrFqG2wRo3mFCbZC9ZJvJha/bZzUNX6D96QKt0FX6QS9l8DU4iSxxCedQfEKNtD6hgMwe3Wyr4N0dVrzCDP+ea5hP/bYdjr+o/DhN3muRki5o7dBGjrix8bIUsw/iJaSmnNkvQrHhiE3HbAExck9iwkPD2UVQQzQ0tnbam45Yi855ES69QeC4Cm+wGLFBLLx1oSHLzbO0E4rN1wjueQdssTVn+0eh54aRyPSyCbxk1vCQWPnA==
    ACCESS_SECRET_KEY: AgBMij1C5qjkoX4DLlcCHhNw33lWbZI4pXhbjuOiFCdjBet2awL46zKpbBA1l9om3Ups2tEWEGZbKWO3pG7K/bp1mCtQPC2ONtZRppEsHy17JFJkwLIcwkbaplDodtvdXMnfbD8GnZHAm/3Wx85BfQvcmEujdDUVAzzSeXPp83NXujXqhu/qXbwKUGzvwILxE2SXcUUjV8oxr8z3gRfqJtv1nLzhHyGi9fAwn0aveRk5T8XdV0TE1jnnHR8QLcJHuKIFQt1M5YINQJIusYHtIMeSnqsOk8D4Oa+Zv2UcEUbeQeZNNKgnX/S2fqrgvvRBnqH/G+nnGQcG32g28Et1PHRVqQG1/PYti3QD4n9D3HB9Mr+oj01ECOosvSl5xKGhybJ8l8tDLI0LJjBLqWLF/jlaCSupVOV3l0j6kGNeN8uvvY1oHI2STWCcY42ngo84lIRjA+86WoeKbSx7mxY98uj6z1NcC7SYyPE/fKy1W6WrKH31hB76QIFwMMw/2HxkI9z2+JRvNUHpAmnoz7NBrMiw70AiqPNfLnQcMfIhnUeRIHdsuB4x7qppf1Vu9ZDVe9SM8e8fzZPyXMoUcRLEiV/pGJk7nUiUNILOl1vWoHSdcK2yxGGqaTYgwIuoKDfoMPJVQntbHOOj6RexVcMiSaMPtoU0Wt+i0h1xNXHFrK4XJYMJAFDa2CNDbrWr3SwIxqWtZqAvyaGuZrqlmIJIU95uq+Eq1EuxMKJm3NtcZLbW7k3gjY8n9h3o
  template:
    metadata:
      name: wasabi-secret
      namespace: immich
