---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasabi-secret
  namespace: immich
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAb8aY+WIIcj7C8X/OotYsYUx6R0IbwlTyPhpEqPsq8cLkwKHdPbGf7BWBf3QayzqqH2ClSS0jEfnvb0GTqdHYBqgjCYQAdCJXHkDktX2mcvMWor34M0qeWL1Irtdi3kk9a0FFabuvpMkhtk9okpR/YlyfDGXRnQuRE7+XCu+3SUHIEHj4gwmoVGQdAVhzSBEraV8ihJoUGKWpUeA61YaEaXzngBnXVmay1QPM746S0Ip9hPdN2B7Vy08y66S2Xqvq4ac3ISOOzZ3QXoXkAFunIjH/BEFZcRQ3edsx6V51YZrMnG0cfsYmeQ1Ze8WTyRGpQw/xZsYTVHeu7EqCS0ogFeE6/8JmHETT4cygJizjM8SVgSCLUq/vM5djh7FlFJiL3GWVDc/Aq7rrslh6fo3M526yn3CKA1/ymH2rAGH3Bbj7sLiH5Bte8msxVPy1huOOC4P13MnE4ssZ4DT0qxSBdrCyX2WdlpStFVrpn4XIr6L+iTntmpEOgyFtQPKw0wGKpG5F1nyAF4NrzlJzODnwIbiZ/qMz+thngdX5FGb4SE7ca95fKFLYsF4yaswgt/VjK3xt7jjs96Svj0a+xAFcze6Wpb1wXtVMS09Frh8YNm41LPPtcYn9ohoCK+Y6iQ0O57sf1gR3E5cDizHD9Lh3mvofyicPfEzZbM+SjkrjYBzTEjWGiv0k5hOzRctCjpa2XMSKygPzKmIYVVnhMm5dApo8zVQ==
    ACCESS_SECRET_KEY: AgB+EcBAC1y/ftkqDikn8fbCLKyycM6qar6kajkQyoQi6xR2z83aowj4KMaZSdu5gYYHzmzBAMExIwnysPFxRnLKgBEeqDqC3H3FCIKU9STzB0+P4nRTZ+7GspX1YefAQSfYmuZMfv5uzR5uJSyvDrbqgMU9W7o2ylrOAk6weZWqIKr/fTr4wVnZld3pK9ooWp2RwQYIQonFGpVuz7BWe+j6WS7T0yjkaSQDx5I3RBfDnyGcKsan2MJwr2Eq2I8rYN5f2WR7wgKt88WvqzHIariQgOq5BC/9xWX0Mnv4d5lG0N6tLTOGeQ6ZVfR+rGS1RhP2Jq0qUvKpPYJr+CnmLuLd+FVUy4JUb7lzpxHXZFbPMDvTIe38rxVhDFG3eD/ucYbp6DurFWBsZgV53CxYOvVPIwEklqhFGC16yu1G7hT4v/z9BledXLdxYcBeaN5LOuaNkiXc5qSIyx/QMEpHef5HZU8pDT5m79qFTafZfsRbwHVQJ67k8ayBJFgWPRL404oZWfPhEEHYlnDusgrc0UJaoax0LfcESAsmRQjBJ3Y2pR6k1g+GbYa+CpkeFFtErG75gyLLOvpw01KHTkg74JysnBbq4M7xID1VFbUpI6iBXGLWdiDL+iWAT3gqhNX99qvd4ByX5ecZt7tfXs+5XGV0foqlahmmbX9xe0SZ00Qb7UpCA2+Onse2+kTz/cgWoHa0deu7U6jT21s0TZJd3ZhVWsv2k7Qc6+9ypQUzAEeQ57W/3cgVvxzt
  template:
    metadata:
      name: wasabi-secret
      namespace: immich
