apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      version: 27.x 
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: traefik
  values:
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ingressRoute:
      dashboard:
        matchRule: Host(`server.michaelthomson.dev`)
        entryPoints: ["websecure"]
        tls:
          secretName: letsencrypt-wildcard-cert-michaelthomson.dev
          domains:
            - main: server.michaelthomson.dev
    ports:
      wireguard-udp:
        port: 51822
        protocol: UDP
        expose:
          default: true

    service:
      annotations: 
        metallb.universe.tf/loadBalancerIPs: 192.168.2.200

    logs:
      access:
        enabled: true
