apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: media
spec:
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
      - name: jellyseerr
        image: fallenbagel/jellyseerr:latest
        envFrom:
        - configMapRef:
            name: jellyseerr-config
            optional: false
        ports:
        - containerPort: 5055
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        persistentVolumeClaim: 
          claimName: jellyseerr-config
