apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: booklore.michaelthomson.dev
  namespace: booklore
spec:
  endpoints:
  - dnsName: booklore.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
