apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nextcloud.michaelthomson.dev
  namespace: nextcloud
spec:
  endpoints:
  - dnsName: nextcloud.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
