apiVersion: v1
kind: ConfigMap
metadata:
  name: calibre-web-config
  namespace: calibre-web
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "America/Toronto"
  DOCKER_MODS: "linuxserver/mods:universal-calibre"
