apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
      - name: calibre-web
        image: lscr.io/linuxserver/calibre-web:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: calibre-web-config
            optional: false
        ports:
        - containerPort: 8083
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - mountPath: /books
          name: data
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: calibre-web-config
      - name: data
        persistentVolumeClaim:
          claimName: calibre-web-data
