apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-data
  namespace: calibre-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Ti
