apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: calibre-web
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
