apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  chart:
    spec:
      chart: homepage
      version: 2.x
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: homepage
  values:
    enableRbac: true

    serviceAccount:
      create: true

    ingress:
      main:
        enabled: true
        labels:
          gethomepage.dev/enabled: "true"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        ingressClassName: "traefik"
        hosts:
          - host: &host "home.michaelthomson.dev"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: letsencrypt-wildcard-cert-michaelthomson.dev

    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
      services:
        - My First Group:
            - My First Service:
                href: http://localhost/
                description: Homepage is awesome

        - My Second Group:
            - My Second Service:
                href: http://localhost/
                description: Homepage is the best

        - My Third Group:
            - My Third Service:
                href: http://localhost/
                description: Homepage is 😎
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: duckduckgo
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
      kubernetes:
        mode: cluster
