apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        ports:
        - containerPort: 8096
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
        - mountPath: /data/media
          name: data
          subPath: media
      volumes:
      - name: config
        persistentVolumeClaim: 
          claimName: jellyfin-config
      - name: data
        persistentVolumeClaim: 
          claimName: media-data
            
          
