apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  resources:
    requests:
      storage: 60Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
