apiVersion: v1
data:
  config: |
    version: v1
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: true
        resources:
        - name: nvidia.com/gpu
          replicas: 10
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nvidia-plugin-configs
  namespace: nvidia-device-plugin
