apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: michaelthomson.dev
  namespace: michaelthomson
spec:
  endpoints:
  - dnsName: michaelthomson.dev
    recordTTL: 180
    recordType: A
    targets:
      - 142.126.163.72
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "true"
