apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: actual
spec:
  selector:
    matchLabels:
      app: actual
  template:
    metadata:
      labels:
        app: actual
    spec:
      containers:
      - name: actual
        image: docker.io/actualbudget/actual-server:latest
        imagePullPolicy: Always
        env:
          - name: ACTUAL_PORT
            value: "5006"
        ports:
        - containerPort: 5006
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: actual-data
