apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: "snapshot"
  groups:
  - snapshot
  retain: 24
  concurrency: 2
