apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: woodpecker
  namespace: woodpecker
spec:
  chart:
    spec:
      chart: woodpecker
      version: 1.3.x
      sourceRef:
        kind: HelmRepository
        name: woodpecker
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: woodpecker
  values:
    agent:
      env:
        # -- Add the environment variables for the agent component
        WOODPECKER_SERVER: "woodpecker-server:9000"
        WOODPECKER_BACKEND: kubernetes
        WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker
        WOODPECKER_BACKEND_K8S_STORAGE_CLASS: "longhorn"
        WOODPECKER_BACKEND_K8S_VOLUME_SIZE: 10G
        WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
        WOODPECKER_BACKEND_K8S_POD_LABELS: ""
        WOODPECKER_BACKEND_K8S_POD_ANNOTATIONS: ""
        WOODPECKER_CONNECT_RETRY_COUNT: "1"

      extraSecretNamesForEnvFrom:
      - woodpecker-secret

    server:
      env:
        WOODPECKER_ADMIN: "woodpecker,admin,gitea_admin,mthomson"
        WOODPECKER_HOST: "https://woodpecker.michaelthomson.dev"
        WOODPECKER_WEBHOOK_HOST: "http://woodpecker-server.woodpecker.svc.cluster.local:80"
        WOODPECKER_GITEA: "true"
        WOODPECKER_GITEA_URL: "https://gitea.michaelthomson.dev"
        WOODPECKER_GITEA_SKIP_VERIFY: "true"

      extraSecretNamesForEnvFrom:
      - woodpecker-secret

      secrets:
      - name: woodpecker-secret-core

      persistentVolume:
        # -- Enable the creation of the persistent volume
        enabled: true
        # -- Defines the size of the persistent volume
        size: 10Gi
        # -- Defines the path where the volume should be mounted
        mountPath: "/var/lib/woodpecker"
        # -- Defines the storageClass of the persistent volume
        storageClass: "longhorn"

      ingress:
        # -- Enable the ingress for the server component
        enabled: true
        # -- Add annotations to the ingress
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls: "true"

        # -- Defines which ingress controller will implement the resource
        ingressClassName: traefik

        hosts:
          - host: woodpecker.michaelthomson.dev
            paths:
              - path: /
                backend:
                  serviceName: woodpecker-server
                  servicePort: 80
        tls:
          - hosts:
              - woodpecker.michaelthomson.dev
            secretName: letsencrypt-wildcard-cert-michaelthomson.dev
