apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: polaris.michaelthomson.dev
  namespace: kube-prometheus-stack
spec:
  endpoints:
  - dnsName: polaris.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
