apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris
  namespace: polaris
spec:
  chart:
    spec:
      chart: polaris
      version: 5.x
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: polaris
  values:
    dashboard:
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
        - polaris.michaelthomson.dev
        path: /
        tls:
          - secretName: letsencrypt-wildcard-cert-michaelthomson.dev
            hosts:
              - polaris.michaelthomson.dev

