apiVersion: v1
data:
  ADMIN_PASSWORD: TFJLajlReHM5dUY3ZFVCVWJQOUdQVjhVZWZrTUFZ
  REPLICATION_PASSWORD: TFJLajlReHM5dUY3ZFVCVWJQOUdQVjhVZWZrTUFZ
  USER_PASSWORD: TFJLajlReHM5dUY3ZFVCVWJQOUdQVjhVZWZrTUFZ
kind: Secret
metadata:
  creationTimestamp: null
  name: database-secrets
  namespace: todo
