apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: media
data:
  PUID: "1000"
  PGID: "1000"
  OPENVPN_PROVIDER: PROTONVPN
  OPENVPN_CONFIG: node-ca-13.protonvpn.net.tcp
  LOCAL_NETWORK: 10.0.0.0/8
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  DISABLE_PORT_FORWARDER: "true"
  DISABLE_PORT_UPDATER: "true"
  GITHUB_CONFIG_SOURCE_REPO: michaelthomson0797/vpn-configs-contrib
  TRANSMISSION_DOWNLOAD_DIR: /data/downloads
