kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: transmission-secret
  namespace: media
  creationTimestamp:
spec:
  template:
    metadata:
      name: transmission-secret
      namespace: media
      creationTimestamp:
  encryptedData:
    OPENVPN_PASSWORD: AgBYLwbZCo8elG5weUpoYEwJvcZiOQr/mGhORWV7Qt+fe810IzY8dMSLDNb82ob/mp9lFTWmcMCeVTNd05HiYgFCc1K/BFzUvU/KT1TLgf05ze8noyoDh8Ot5PZ8U2p4VE1b54mvTJrXthZ9ckoyOJuCWjymssBOAUfBJdQYnohbLOEpw5GiSvPsp5r7QMK7FCnou4oNNivZJBn53c9Q4YNftJ96YFWAj1ydXPPY8E8n6JH+txeDjPRM42RTZm2GzPqbprdyATJzgcDg27jJPTkGD3iDWmfy/QaEoFsUVi4ZrL+KWAJ6oYOx0pf0heiW043Gc0Xhkbcsca/t6bk7Jyd3OUbv90zJZrzvJd37uax6zzAhO6eEA19OzWK7LD/rKU7XD8CEyIsw7z8Xby4ZusbfzkZJjRDPVQhIHMK+kDFKGkBMccBZaYepNJdTd+f/iBiJ06zfPln8FlLAoEmK8/74WphHjXspIt9el+lCcs3+FBd/SRO96s7+CoWNMvwq4RIl5fF+0QxEIce9w0FwpN3heiFl8l7LyCWWAH+0Zud+rCQZaPctlccCOP5t95eLcIhP6XBhHyqIElWUNaGulpruIFwpoD1qgHt/hz3opBIoUi3VwnyoYPDlW/JU6ECzmMXvBaOtnvXU08ygRjWxry0RvzXq7x15j8Jn0RI/09W52bkQGb9KHCGebkt0Z5vx+YKBrhCOxiAhDKzWTceX3OTamx4ofJsoF2IlSTLjCQueAA==
    OPENVPN_USERNAME: AgA/DHbUeCestT6mZjfwJ/JbUJ3wfhD3M5q2XP8xM6708uSxG+B6EDlcrIkM5+QAxioZCfeRtuv8pxCgb9qgc685ogOv+/C6k3S9hgtTlAmUMxCCLqgCG+HhSwVBj1YNpGcBrnpsbTbvM3NlaRJbMf+fFtYqYHS8WelqEZisAECIAuYkswxX/0wcViMlgTUk+vsd8KtM4z4AeH3d6u6ZczQTHnBxxbiOni8nwXepPo+aN5PcAsAuUVvp4g/gL0Uum3WxkjBnYA3C1+ez1liHXA36pqd/LVafLEcBNQyo45nhCi/Oy8QyGI7M4voU3A2dOJddn0Gssc99HyHEj6QjVr1sAE2K2gyFlqB90Hk/RkhbWSVnkJtJwgG0hFgD5NHLh+H0GcvOqUMOEVcYyL//k2Hw3dRvtQkvDdYZ16Kddpcueu8Q5Yi5k0cBs6c/cc7+iHVioKiJaT8OO1MiYGwR1FhwkILMvSt7ozkOsAFpqYxETwYpSeTYxoPyNyc0LfLdXdJ4aDzgZyW9cV7gc4yg7sOjM0wqv/FlGz8RQv+/iQLhoYh5kkm2zA68Of0ytIgitpBWecmuEnCFC9gR9llx+M3qkoQB3Dfvwom8DR7Xs4NOyvx8YzR9adPArc9jHIvqZfW7LVLubCS7PhhMsaKaF7brixPLNija0hCFv6JDn247MJ97KK+1byA9ZpCgKlINO+DyxJqA3Ljq/Vea9asgy9vA
