apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly
  namespace: firefly
spec:
  chart:
    spec:
      chart: firefly-iii/firefly-iii-stack
      version: 0.7.x
      sourceRef:
        kind: HelmRepository
        name: firefly
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: immich
  values:
    firefly-db:
      # if you set this to false it will not be installed
      enabled: true
      # environment variables
      configs:
        PGPASSWORD: "password"

    firefly-iii:
      # -- Set to false to not deploy Firefly III
      enabled: true
      secrets:
        env:
          APP_PASSWORD: "password"
          DB_PASSWORD: "password"
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: firefly.michaelthomson.dev
            paths:
              - path: "/"
        tls:
          - hosts:
              - firefly.michaelthomson.dev
            secretName: letsencrypt-wildcard-cert-michaelthomson.dev

    importer:
      # -- Set to false to not deploy the importer
      enabled: true
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: importer.michaelthomson.dev
            paths:
              - path: "/"
        tls:
          - hosts:
              - importer.michaelthomson.dev
            secretName: letsencrypt-wildcard-cert-michaelthomson.dev
