apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-db-pvc
  namespace: ghost
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
