apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  chart:
    spec:
      chart: velero
      version: 7.x
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: velero
  values:
    deployNodeAgent: true
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    configuration:
      backupStorageLocation:
      - name: backblaze
        default: true
        provider: aws
        bucket: mthomson-cluster-backup
        credential:
          name: velero-secret
          key: cloud
        config:
          region: us-west-004
          s3Url: "https://s3.us-west-004.backblazeb2.com"
      volumeSnapshotLocation:
      - name: longhorn
        provider: csi
      defaultVolumeSnapshotLocations: csi:longhorn
      features: EnableCSI
    schedules:
      daily-backup:
        disabled: false
        schedule: "0 0 * * *" # once a day, at midnight
        useOwnerReferencesInBackup: false
        template:
          ttl: "240h"
          storageLocation: backblaze # use the same name you defined above in backupStorageLocation
          snapshotMoveData: true
          csiSnapshotTimeout: 1h
          resourcePolicy:
            kind: configmap
            name: resource-policies-configmap
