---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare_api_key: AgCnbPF8qdEJkV70GZtytvOmQUHEF3KiN1UtxJGbmWopRc/OB3414xEXRfVmRJ5UJ64tb1IvokmWOwfXbd+RkiYuDJEv8TNHv4uzpmnOLghbbeUFSf10vp8jhiNGzKyRZGwfaPYU+x8Nje5t26CJgSS4DzhujtvBOczr+0GPV48Sj7kG7MVLk+Y5Khnq/4BiCBB71dsEJfvHBb3bjEe7LqCBMHUwtAZjunFd9YIg+Wd/ZiDj6rPZxhwyAchOoUUuPNumwsP2IYz8/IuneGCQMoW+pgN4GgJtk1IrQ5fn9p/IctFgY8QK06LPgXSlUj2/QLvvyXd4Ce/F1KNE5REhKVbywF60KdgtdgFnrfz7YN88vXcxDU33ikXdwF6Sk6TN0Of241Wb96H58U6l1lMqxaityl1Q6GYodsiB7j7b3eDEZBpHCFiQYZxdGfUKe2cC1fdO5EKGeRaN9pJnTtcNj5M7orqe4dinrLZZvJrhnjapxJk3opffJKerrOIDaYHoBIdGySfiirt0mZeYRTaiO2nECKRc6ohYBodlJD5ncYZxdgm5d4JzhDoaaen2jR2aAUrFNjWo5zDVLejiciP+vQ/Ed3M0RE+kxn5Ek17OjuMmdpNoOru5kydtCXE4uIouM9+qbDjCNebMbHCZMEjfT+Ulhr8pP6k3BCr0EgAIzFDVOBSVKUVowcuUhlEQrR2HWROANKSW/ltn6lc15vGcJ2dx19yV4g5BnMMalioVckpwfkcQLRL4
  template:
    metadata:
      name: secret
      namespace: cert-manager
