apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: kuma.michaelthomson.dev
  namespace: uptime-kuma
spec:
  endpoints:
  - dnsName: kuma.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
