apiVersion: v1
kind: ConfigMap
metadata:
  name: act-runner-config
  namespace: act-runner
data:
  GITEA_INSTANCE_URL: "https://gitea.michaelthomson.dev"
  GITEA_RUNNER_REGISTRATION_TOKEN: "PWwo9fPd5jFTdGi9LrUuWHFCXQi4xPosuQUpmQjX"
