apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: wiki.michaelthomson.dev
  namespace: wikijs
spec:
  endpoints:
  - dnsName: wiki.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
