apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy-config
  namespace: wg-easy
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
