apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: transmission
data:
  OPENVPN_PROVIDER: PROTONVPN
  OPENVPN_CONFIG: us.protonvpn.net.udp
  OPENVPN_USERNAME: wSNJV3UTu7K8fxBV+pmp
  OPENVPN_PASSWORD: fh7dwMzYzJGmHgTo5nTlirjaO0LANcUa
  LOCAL_NETWORK: 10.0.0.0/8
  OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
  DISABLE_PORT_FORWARDER: "false"
