apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: transmission-test.michaelthomson.dev
  namespace: transmission
spec:
  endpoints:
  - dnsName: transmission-test.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
