apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-secret
  namespace: transmission
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgDL/UEcrP9Vi49S7kwCuJFUqV7eXwMiXq7I+qDr0tWlzSwYQeEAhbpGIOUoDzR/dPWt8Z/cgvUtMjzJoFT0LJvLmAVApENWw58y54dQJUHM+aXc4C6C3gWaq/+Y2MFvOop8HWT1ZzP5vt2fyGq/kFbU/jnpofB3Uyv5tZVLKGMGtGfbcbiJC2id5I+fGDyS3lYtmZ08Jqbgs/1T7FSBve5H75gIDSKvSJgINHi73Mzk5rhQJFjat1Jgp2Ag+JryjrZGqgL1+9A07+68F35oYleEvHqHNHkdgeY4lihhp6puqNX58rA4sd++QQGi87nIzMKjTQBTTwyo/a8k/yWJQIFC6CbBZJqmsyACH2qg07mHP0Jz9UN9yiiqG+aU2OLdfYRQXpCbFRoANdRIJjlh3udPqkNknY6CY5VIa4eWGcjkPfKqo+xm9SfmAulgpDWNOi1PHh3gbnfBCN+EDDFnB8QGYtBmOftpAMItfzr3xvXmBNp7yjw7NYwxNe4tvvNWPXn5V4YnB7yvpMrAR88jnQSE2GamrcwRG2hTJDp/6L3iAlbRGoAsZsY0o+jWef07DlkIahLtSwlALCIhZYF8N9Y6Qbi8Q5VRcw8V25qmo4rYSYvbS6NS6CbnXLLb3o898/raASu9dcjajuNLZS8flLXJPLRVcI/U5dvSpkRwWp5988b+yBXz1AylK4jr+r5Td4tRbcHhbAJrE8pvdJUGnL78l8nJggCZ3xBbHXP/XFan9A==
    OPENVPN_USERNAME: AgC6znv7/KFPRR1UELHBbq/hvdsrFjwUpYErBiPi4MwHbgPeDZ8WJaZEK5ECRWQl4IshasdO98DRZLZvf5xXK4UjasWRXblfhbZHgkAfpfoJnbBg8TvR1KFmpMlNZ0lYWziGbPzFTQw/jvAB5frc1d2sTK+leUte4OyOvpYIlAu2Kq8yIl2s1JD+R28vohvuCBXmyB7B3CBTlroW2S1jBlcqk0uBI7yZVFiOi6tORWCjYTKayJOcExOL3cycB32WgQRxhWmHP5JfUU4EbgDNwvfkBpLobibEYUeh41Hq6WPvMN7vTVOok4PADC2f4kCcTVNpirhsbc/T3acuU9hQ5g8xSiZXq0S0Zlr6yM43i8rXvztdv9HWEGrA6B6gcTeWge7dhPoSNyfnLlpwpXbsoXKXpZdZ6Re3HMXxWPTV3P3xWwMzv1+7O2VXOtM/dXWfPdPDE0qT1FEP+hdzyuZm3uX1X17HKJYD58isKWfEBxq+PaiTMToPvfYQswiOBy9GNfaRfcKxUIOedzuDLc9qOAl+OoLwgq1N+RIrImDepemMqvib/TEPRUrNlAcmwChabu1yHGr8F/cojFNRnyUDC3iWf+oflN/OgtPB02Fr2/3g/YEsuJQzGuavgp4B5D5e5z2lgO4F7EDQtAUsaWr40NH6tA9Rj2hGemSsG+MG+mylTUDULHV1BsGh0C8TVlZJ7v7oyn9xHy3ALQdWOZJnIohS
  template:
    metadata:
      creationTimestamp: null
      name: transmission-secret
      namespace: transmission

