apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: transmission
spec:
  selector:
    app: transmission
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9091
  - protocol: TCP
    port: 51413
    targetPort: 51413
  - protocol: UDP
    port: 51413
    targetPort: 51413
  sessionAffinity: None
  type: ClusterIP
