apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: plane.michaelthomson.dev
  namespace: plane
spec:
  endpoints:
  - dnsName: plane.michaelthomson.dev
    recordTTL: 180
    recordType: CNAME
    targets:
    - server.michaelthomson.dev
