---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
  namespace: plane
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAPLh1tuWunpFvJ8Ajnfc4RmhShcNqhYoSzSzGUdTEAn9Uk9tEu9YMAeKQZvnxdz0cT7Vt3CYo+9h5kVshTjLl4XIe+/r19skz83QdHzseEacotmdJdi+KQEgW/N95O0PLQlppytaGx5DtVFABzSzNoeTg+taw5WFjiwhDhYvgFDi7GI+T+pgtCyhTPNvztf3p6DI1D1jd+DE7lhfD1kI/jf8QbzncbogleDCTn/klyJHo8xyIdyFGQf4+CMHhvr74u+hezfOrAO2DcUDaKTrXKe+wDgIfOI8M5KZKuDShh7BXUJ39JzBnuq7sNwrKW2A56qfYBDtN9hDzolHtR7S5H7IcCXDU8AXeAUZUDL7TQuGp5xkVwvAa/CWl7uOOpVsoAlwPsAElHZFXb0FMNdnzv/kPZSBdEnR/OtQ37aexhbYJJ15a1HMumefxuNcjEd9Dpie3a5mIvRGzDRiEjr8h70nUy57mHNm0Srv2MX7EWIlk73bDsQoOymtMTAZVp+YI9hIuYxiECf6Vj5pUUJZDu1ZXwsNnMyyD1d53VTiwirqWwmH0yc6SQMPoqpE6Q3zPwHY66uCDSszT0i4SlSTToDB1hdfUSd0NcTQ+2z96NlvxthuNpSRSwDE1cphQr4lWqArCv7Eez4huLy87X+V/g11BJEmjhdn/x2FtYNDKtPP8KAIvLxfFZ1vuSuco6O9Xlp/xq5usw0IW5yq03FjtgheoXQav4Y8q1kIcmIAEpQ9eiYH4/E0xymBGa/UHKSuguI137
    RABBITMQ_DEFAULT_USER: AgCMpxW/hN+6OVeC6uvffZlm9hpjT47BA8JqLHiJlV6/yjb4hqIFlQV8zy7JR+WtT7g7ra0guUv6eQ46wjvfq+vp0lJttEA6FXCK2cUquRGz+7fy37iByAvE8/Hes+EoMUBFT5qFm8+keStOhRMsUSqlINfb5WLSW2G/EkvTsYdMCUEmLAhYxxv74bLEzIo9WyEdm5vecciT+ExvsJWrga/zUpRYPQ9PSm0GjbEiODYU1pT7atU1CRVEH+3eD9uqcCoHqRF8Dz4PdvE40AwXOA0zRjUhN+ZyjaB2Ad1bfv+xuxFSM99SEY8f+XK8dV889wp3Wc9jmBzoI1OfkC2vNOBmaM9DyvpaSkVgTHDMV6of5Aa2bkYFiNfGVqIQuoNn4dJF42n0Rfa0ehFHHTuQKBgDAta2QSpxJIgAMaiBRAKjAfd1eQRfKaashbU3az9PtWtuOgXpHfSD322Dd2zDR61WNyX1GEcCibtz6fy4OqOSo0YXPNOf/cSW0tp168JujD1bcEQ44uq/xmL//2Nznw2qJ5Q4UwTcMcmOSb3XNXAfgHcUr9751d2xkGKDY3x/pbyCz0SUIbw42bxDHTAzhfpszwyHMgMuFwhMkmzP/XW5/TGCqyarnPS78Q9L0H80FG2kubN/WHRZgjLwXO8x7BY483Ypr2Sh1sHCbs1bgEiHiZLANQD/nR7b9LZj9cDPbGTaOJzJvQ==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-secret
      namespace: plane
