apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskchampion-data
  namespace: taskchampion
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
