apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 7.x # auto-update to semver bugfixes only 
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  values:
    sources:
      - crd
      # - service
      # - ingress
      # - contour-httpproxy
    provider: cloudflare
    cloudflare:
      ## @param cloudflare.apiToken When using the Cloudflare provider, `CF_API_TOKEN` to set (optional)
      ##
      apiToken: ""
      ## @param cloudflare.apiKey When using the Cloudflare provider, `CF_API_KEY` to set (optional)
      ##
      apiKey: ""
      ## @param cloudflare.secretName When using the Cloudflare provider, it's the name of the secret containing cloudflare_api_token or cloudflare_api_key.
      ## This ignores cloudflare.apiToken, and cloudflare.apiKey
      ##
      secretName: "cloudflare-api-key"
      ## @param cloudflare.email When using the Cloudflare provider, `CF_API_EMAIL` to set (optional). Needed when using CF_API_KEY
      ##
      email: "michael@michaelthomson.dev"
      ## @param cloudflare.proxied When using the Cloudflare provider, enable the proxy feature (DDOS protection, CDN...) (optional)
      ##
      proxied: false
    crd:
      ## @param crd.create Install and use the integrated DNSEndpoint CRD
      ##
      create: true
