---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actions-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgC85krUdEalCC08f5qRA8QPElwNS/1uKxuIyVhq3HtSiFFyUn6TdIpRt1rkB7u9xAkWkm7otIZ9aEN6CBjYin9RuzLsJQbfFZtypmR37FfZyDWEr5N7o94uU2zwNt9wY56v+NHS/fhVKP1HvOhxPCvqFuX03NJI6ThbrCrCPqUZsbhxovCMGZoR+Fx9GvA0ziLUu/eHKrGugX7bLI53ik7TTGoW7clMbtHLX4zI3+B8RQCxMokDghmjF7O0EdA4aVxwS9DERuMNH0V3RhZ9QaN3xA+pLJPbml7iqekQwpR1c1YruOvB8zZUZmFGBcd0yStdiZX/coX0YRrMaodeULc0gJ8BmcgsnQh24pPxkA138s3hX7UKSAuLDuw9dc3+6U4Cf9HIWXHSQZXxicUO6PUP7/loeSOksGcM64P45CHwaEvdOXUbYto/fDm806jnql1Jbh6RUriie+oHLMM85fC8c2Qk5r6YGMiHwWEeJdtmVv5o9ejeTmSj08r/sOlPr7j4SyLxWBT3O4XpEYPQJPCObkG4xubZpUw94zJZyYyQULZXGgiQOgdIaESK/eIj7QNLX1wD3Q3dDdbhW8tbknbyE+0qRC5ub+qcBULCVOzS5SZlgu0BtNntmBy8QVUOQByCroKyL8gs8d2mn640fp23iAS85FPle1OFBFhIX4DpaLE+8btT9ztGRvyMxmu1VwKNZjuz0toQ5FbaRJUvPnLz56jwYAucdsoL5t1d5sy7ECTlaaNnS3ni
  template:
    metadata:
      name: actions-secret
      namespace: gitea
