---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actions-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgANkIaid53miaBao2ZC6g8hkOCXCV4ig0o4a+615V0EEyO5XTgBfN+DRoPdy+kLu7p6FeHsgbe//amOtwDBeZcdzk47UA3FwpO4lJR6X3yDjiXrK3o5QaaoPXwBocq4merlf98lWnTsXY9GQ8zkadQNfArGI6bFifs1CXWOGDTQDb8vMfW8owUTVOZPuT8ZiA39FgvkPCSZvbJGkBGGTaYR9BXnq1dUjTP9MqGA6mLKseljhD2RPAP1UvmyZKC9BEiqrxy6lMbODTEUadYLD6sRk9/17yEYTlWeG8v5VnZPCWyDdaV7CJKUH6sRAHwuxJD7eTijjNM55wZwGdfF4zFLGDJ1NFVyJJUdF1Sw/lKx3rcu25CV5erOsqAzfd+NkzqfV1Kq0e+eOFsi9BgN8k09Jy9X8BPIh8Rojpa9rvdGkGBu3v5LPtNUTRnEUfCnE12M0hZAt5alq2GDOeurFf0ThWg4XmrGSGdbkr5VJ3C8QClQwO0KhzuxAqx6kZ5y3AW9iFOQDXSwYGFK8O+KLBEVB4435kFFKGLlBLOep7CpFAskREQ9osv6t6/RtSqIApqVerx5cRHWmm793ot0cJaIFJFjdqfokgEst3xzsbfXw2DFh3PkqPpWjRfbACtL0necixIdxnBDgXW/7JP44Iwyweb+M0fIOoITGlIgeTIYcUddf350b91ZU5GueYL07uN0N0+amPpeUGDTeesNJqDbSaYTmpA+DKSfHSUKkGH+djP1JaUNdWgy
  template:
    metadata:
      name: actions-secret
      namespace: gitea
