---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: actions-secret
  namespace: gitea
spec:
  encryptedData:
    token: AgCA1Y6jt40beiVeCGlfXhbHz0mPvMa+YILLIdTtnW4UXmj8+9MWU3udKQZRfD5l/LgtHxlvjQGuVKo6qqMoR8IcL8At6KtcDX2VNKTcb5XooIknOooX3nrNxOYsQ5z0HCbHmOeK2q1fp2ibdpHi5N0RV0mPgi41USSiI7WfGWWaSfYDzQB/qp33jfF9Eibn4IyMOHzSk0CknBewn48HmB2/k61WUy3m/1/R/fkH3hIqDzUB9GrNwhrM/Bv3ae3bqQ5FPIUaO8H+4TVNx7JV1z8/4UUK5r3+xtE7XkFND3ukYgVk7wLtqUx2+HFFVpH/UqwFuEKajSVZxLExnmCG90+pPE7EqgAUtlT/fV8NziijnAS6iG+5TsnH1b4cgNPHDvYfFF+ntWCOS5x++UzMg2jYCDETST7KOH7KS1tBgMayzr8PSF3aqF1H3iXSYF4+gm4p539ppfa9aaP5vLYcldCFdzbL1Qkb7MDnWgmWssZujDkeW1sweg1LEtgHijgxytvj1b2q6uGmfghb97Y5TjWg+vLk4ReQb0COWvz/+2UCZ2nudaHHZsOJJJkZBSWPgWfuuGfwK+6GuOtxntWCgcbESX7qarsAJ/eP+17Cs06ti9IzxGHMVK0EFnwdY5UOZvpsVZRnvCatShNS30YF19ZP72AIV4bPyCJUIWqs5eXWkU7viyQPe57cXPE8MU9ej8OKCj8KpSoCcLct19+Ci4sAHzhSocEdeHHbewuQDELWzLmkSTUpfhR3
  template:
    metadata:
      name: actions-secret
      namespace: gitea
