---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgAJWEA7T+rqG3/J6h+boJS/PZUM7dVLyvgMl4WfpeGsuKtxOm6f1+I3jblKdH7LBpHECNpTPBdGUDQC6om0U08MzTDsrKkvWlEiToPVUCPRj7iro1pvAdMf7zyOw2VUwOPca2WfpnYntrGqkB8MDJO/IQRK3QMwaZHFKt0jH6JhE0gRcAC+iCIdnQkxzm9+K4i7hCtUxIsDhg6Ze1NdLoGPNeAuedzzzheLU9QppOoqxycoocyEqz3pYMwwZ6DPCX794T2gvrxHSDqdF7tNJNG2xuKfczNfUEjYT1Y414huLW378t450SZWrCNKaAHh1zyp8yJiT7GHh/ffYQ+UZeIYm9Yuiwkz1KwW2TVLyCCQWle/Yrn1tV59gtvwn4wm8Nkf7H7+9okSNM/c+bi06Wj5tupwiwnNm6dz8FVnrTFf90ShMRt8/8fBQnX/hD1Hh7oloplOXEwrIdQDRLekM+JCjm76mmss/oaBBBS3Ieb1lLHNyMYdaQHrjJIzi0Kvq4S+fB8EMRPy0SHk3BdFiNYVuxk8Dw3CkuQ28XMTY6YIXIfda3+lw0oNL2DTZ9wy+evxmLWXmx/5Q91rWw1x+uTgtzESUZz7aNgVD92BaZcAjIjsWcEHXVcYL9801Ix0AoEx89syZK5qwNeBXoeEHwzf4pdHLApo1wmgckqxNN+Nc2QfsfsQ7L73MTz88af1PuXODW9Uxz4Va3FePzq/SYW/x9oLry3yr6VYT/rFb14=
    username: AgACGyb1YXmw84arR+rcQorpcSrJlybawky/G4UjccJSiY6ZJ2xPQtbyPMwXWBCuocCCwMbIoyTI5QypK/4pV9BCyE2Gf3ZeONtUu0rYGCiME+ENMJvSjkHZbHjBKnpGYxrlECmFF0QuLRS4D7l2EcTm3hMk+PRXPhZUazZqKA1QkQPHromCu7NRv4zqba3ztMC9/MeYhRSJ+02sf6cuihONR7YbyVDACc7QvyWOobuM2xBdHvc6fTRhzl0suV55L3uR/QAro44u6T3+cX8qtuw5955tblGkbGNh+9sHcpBQkwkB+4cpOKEIFhfYOjIpGTDZ9J2jvWkLuze516/AQseq23rG2gI8Kt1uT4r4PpSd2x+0fqVVFdzijn75L401I2qFzR5NivOq8KZ8BhqRcUGw5KnZX/5pVfZK15c8PpCCXLxh93aYrJONt9DXFbYwxfOqHS/hIk/7WzVzAzDtEgZ3OPGECf1aqq6KdAHhkq7vXhK88Qq7acc3X1rkqHTjLtnpZD7i7pXuOKOe1JV1Mp7MrlDjZhWIO4Ein56RDPqDrIdWJxGPMmU34jiLqnfCY5Y8LTKRJMz8zVtpI9GU+FdzO7hBnXxYRdO+EaF06vx8Y485O7HLB5MHuIXpPsnkVfj9bhaE9+/y+IQ5Nd9AD1g1musSt9M+lUxBBJWdTx4VpWqrOABZUjCHbHlMhuTB+xtEai+fHtUpK1kfcw==
  template:
    metadata:
      name: admin-secret
      namespace: gitea
