---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgCiS6XwpWBcxeiLm+jXV/q2GU5mepht9lk7ORVPSW9iT8fAZL1CEM8A1VPw93Lh2+q30ySR35UrHvZlTObxwkWCGIqind1vhgic1XHeZI4DwwfM/OAFD1suf/oCVagqimztLseNJZuZ2K34onUXrL/EWVlF8jwenS1kvOgnjU9xgMtjEBTIGWw7UnlNN6Www5el+lFmnRdbjsHnTb/GrIppwk3iQvNelQR8hax2w1nMJ1t4pQ48lAspbxTzUQNt9xgqZ1o+uhjriRM+sLbV/UWBuFKWUXP1///5eny4+FEjc8bfqRaKTthJnpzbw+gcAet7jkrEach/wAhqytM6/4T90jZBoLuI7Te/E2dCTsbri0NObwPNBJvbHZInyBUdvH6rseujfZ7WOOgbFkl/cYohm/FSnc55rFLTigP+qyIeh+mEGaSOizPUc8awEpYzaM055liVHxTduD+qsDo0L8NA1x5rs8DGOyipycvzSfqEmSg+vta4fSYxQh2ZV/kGlQjEmMMkNrMYq46mQSQG7rpwx7vbLobW+OU7MZv6vTvuQCZ/C/Ly5JjFgqhY3bjPXTDB9hLyY5F6bSXn6m3f7tKWCxTUdZ8YC2Q63/FqxL0MYc99vx7HKD4RfnckdkZiY3c7WdIR5lOpXQfrNCt72pHrebBX5DsQj9JGK5jBd/tzppC6hN1Cx08BzrJKhGYJkCLWaw5fowI1wXzlnS+RIGAvTH8y4bBCvifV/RQw/VU=
    username: AgAEretvZVUQk8O9kRmxxkiT2wY+EAT5OSrb2l0WTVjle6FC7FEOD84OQm9v0FFEXM8TSzbuQZ/TD/YcWmbIHM8aJV6t2fpNLipoyv4+BJqOVxwcoaBxe3Hvxs/hQjv+74pWhSVQTABZoWxle4rozHGtcBYjkTIG/Y/wUGBkkGJGyJwd/51IwtstkzF3vyKAXjiurzc9fMV7PeOsFJEsRWHhT2ZpvOUuFzvvTrw7ORePXKOuJjwKl4wWMMLjzTSGl9UfzinKjA4wNqmAnkjScYglDwaEu40+gC5zEmOv1/O9d4dzEA5FeRwTA2HeNjx612nloS3+aNUdOyGn+2OKO16MOAhpWRpyxjICww/5TAFZ7pwzPHe0VeYNCfEPBmHN6TM5/98hUFhGbm8AD3peIfZmf12LMNEIeuSBA7ZEhOb8PXUoUKCGZMpFfzWpdKatt5KEnLv1RYIIHIJZtD7zjBSCWdp9Jk6FfRNWBS+smN7eWjyHwNKBk23abYJg/tuE05BzMI9CGr0F8X1XU14PGuHWg98pLZs/XXliKxLsX2F2W5YmLp5suwKGIMwTDIT5hOntKQexKiA9nw7vKxl7XE5jH6ytqiFMSh63iKbUFfNrUXxrn68yaQrVEm4oy2/GVfgBh/HEjg4Ad50zQlp1RDET5ThEGHXp/hbDwPhl0KHKSs15w3ywBUw0G7yRWaxDmyKs4TeZvQnUkbaAtg==
  template:
    metadata:
      name: admin-secret
      namespace: gitea
