---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-mailer-config-secret
  namespace: gitea
spec:
  encryptedData:
    mailer: AgAHds8UNnpdceJSZgpdkdbZgisg3hDllnPgXKtW1ie73qIPCXbE96bKIs4B+mHX1Y7FujtGPNJAdWC3B+qoUEI0JOGtUtikf8mK+PK7lvtXTXz8bk164boiH+RwAhDUEUpr9DknUYR007NE1W02ZOWF0VkRrK97dF4uZ2pKqHFWkqbjY5Bw5WkuYZ6uBgsqH+LsR+J193ayrKrzsEJG4Fc3WzJAfqXs4GGT4wvlLif70FNzH0SEHdjE+mE/TftY24q4uf6NMsZqBygw2aqpjD64IbwNNSrP4yKaS7ea7WdptkfJjblEkhYdaxeg6irBXtyLwJ7aRD3r8hrJ5whjivGMo66Gnv/EYNb+UwLgI2/Ood5kRy6Q7MsTPEAoscdKxJJaIYAbvKymHXj1C9zVfVi3GNWHUaBmjHmyRA6PzfaGM3P/ZibS7014QnxdJR8qM8MgGQ3xLWMNVhCV03eUnYBEfxNU/qnx0DfNRNMHGny43xk/cwPdh1Sm2B35i2gTSldMjqJgguCM6I9EzorBm33sFjfTf+SQ2C04AppFUdgReQOVH/AEdNjKTP5tHftqETVOXrTUzGFc/1FwE1zM92a4/sRrhgspSE2QQbMt6HiTCtX5oFBmpp6ezhPH5dG+wOiwcd/07QZxJ5bGIbFXfz8SvFYyWM4GpN8h/ndrRs5ldYmAZykUF++YAC794O/b6cFyl9li0TlfroyBagziBFOqELIbXW6Ni+GP+G0J5EH+wJg=
  template:
    metadata:
      name: gitea-mailer-config-secret
      namespace: gitea
    type: Opaque
