apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  chart:
    spec:
      chart: gitea
      version: 12.x
      sourceRef:
        kind: HelmRepository
        name: gitea
  interval: 15m
  releaseName: gitea
  values:
    global:
      storageClass: longhorn

    replicaCount: 1

    service:
      ssh:
        type: LoadBalancer
        port: 2222
        clusterIP:
        annotations:
          metallb.io/loadBalancerIPs: 192.168.18.248

    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        external-dns.alpha.kubernetes.io/target: michaelthomson.ddns.net
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: gitea.michaelthomson.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - gitea.michaelthomson.dev
          secretName: gitea-tls

    persistence:
      claimName: gitea-shared-storage
      size: 10Gi
      storageClass: longhorn

    gitea:
      config:
        server:
          SSH_PORT: 2222
        actions:
          ENABLED: true
        service:
          DISABLE_REGISTRATION: true
          REGISTER_EMAIL_CONFIRM: true
          ENABLE_NOTIFY_MAIL: true
        webhook:
          ALLOWED_HOST_LIST: external,loopback,private
        mailer:
          ENABLED: true
          FROM: gitea@michaelthomson.dev
          PROTOCOL: smtps
          SMTP_ADDR: mail.michaelthomson.dev
          SMTP_PORT: 465
          USER: gitea@michaelthomson.dev
      admin:
        existingSecret: admin-secret
        email: "gitea@michaelthomson.dev"
      additionalConfigSources:
        - secret:
            secretName: gitea-mailer-config-secret

    redis-cluster:
      enabled: false

    postgresql-ha:
      enabled: false

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            password: gitea
            database: gitea
            username: gitea
          service:
            ports:
              postgresql: 5432
      primary:
        persistence:
          size: 10Gi
