apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-cache
  namespace: woodpecker
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
