apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beaverhabits
  namespace: habits
spec:
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
